version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/risc0/rust"
    open-pull-requests-limit: 0

  - package-ecosystem: "cargo"
    directory: "/risc0/rust/methods/guest"
    open-pull-requests-limit: 0
