// Copyright Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: LGPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU Lesser General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
// PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License along
// with this program (see COPYING). If not, see <https://www.gnu.org/licenses/>.
//

pragma solidity ^0.8.20;

import {Test, console} from "forge-std/Test.sol";
import {IRiscZeroVerifier} from "risc0/IRiscZeroVerifier.sol";
import {ImageID} from "../src/ImageID.sol";

/// @title Groth16 Integration Test
/// @notice Tests that Groth16 proofs generated by cartesi-risc0-cli verify
///         against the real RISC Zero verifier router on a Sepolia fork.
///
/// Usage:
///   forge test --fork-url $ETH_RPC_URL -vvv
///
/// The test loads seal.bin and journal.bin from test/fixtures/, which must be
/// generated beforehand with:
///   cartesi-risc0-cli prove-groth16 <args> test/fixtures/seal.bin test/fixtures/journal.bin
contract Groth16VerificationTest is Test {
    // RISC Zero Verifier Router on Sepolia
    address constant VERIFIER_ROUTER = 0x925d8331ddc0a1F0d96E68CF073DFE1d92b69187;

    IRiscZeroVerifier verifier;
    bytes seal;
    bytes journal;

    function setUp() public {
        verifier = IRiscZeroVerifier(VERIFIER_ROUTER);
        seal = vm.readFileBinary("test/fixtures/seal.bin");
        journal = vm.readFileBinary("test/fixtures/journal.bin");
    }

    /// @notice Verify that a valid Groth16 proof passes the real verifier.
    function test_validProofVerifies() public view {
        bytes32 journalDigest = sha256(journal);
        // Should not revert
        verifier.verify(seal, ImageID.CARTESI_STEP_VERIFIER_ID, journalDigest);
    }

    /// @notice Verify that a tampered journal is rejected by the real verifier.
    function test_tamperedJournalReverts() public {
        // Flip a byte in the journal (corrupt root_hash_after)
        bytes memory tamperedJournal = journal;
        tamperedJournal[95] ^= 0xff;

        bytes32 tamperedDigest = sha256(tamperedJournal);

        vm.expectRevert();
        verifier.verify(seal, ImageID.CARTESI_STEP_VERIFIER_ID, tamperedDigest);
    }

    /// @notice Verify that a wrong Image ID is rejected by the real verifier.
    function test_wrongImageIdReverts() public {
        bytes32 journalDigest = sha256(journal);
        bytes32 fakeImageId = bytes32(uint256(1));

        vm.expectRevert();
        verifier.verify(seal, fakeImageId, journalDigest);
    }

    /// @notice Decode and display the journal contents after successful verification.
    function test_journalDecoding() public view {
        bytes32 journalDigest = sha256(journal);
        verifier.verify(seal, ImageID.CARTESI_STEP_VERIFIER_ID, journalDigest);

        // Decode the ABI-encoded journal: (bytes32, uint64, bytes32)
        (bytes32 rootHashBefore, uint64 mcycleCount, bytes32 rootHashAfter) =
            abi.decode(journal, (bytes32, uint64, bytes32));

        console.log("Verified step transition:");
        console.log("  root_hash_before:", vm.toString(rootHashBefore));
        console.log("  mcycle_count:", mcycleCount);
        console.log("  root_hash_after:", vm.toString(rootHashAfter));
    }
}
