// This file is auto-generated by `make image-id` and should not be modified.
// SPDX-License-Identifier: LGPL-3.0-or-later
pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant CARTESI_STEP_VERIFIER_ID =
        bytes32(0xadddf33feec474903934d62f6b7e56d12029a63a4f1ded6117626d7033db5fb6);
}
