// This file is auto-generated by `make image-id` and should not be modified.
// SPDX-License-Identifier: LGPL-3.0-or-later
pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant CARTESI_STEP_VERIFIER_ID =
        bytes32(0x1d499d8997c819706d2ef5b7275752901a3d642d93278bbc40516cdcd068d17b);
}
