#!/usr/bin/env lua5.4

-- Copyright Cartesi and individual authors (see AUTHORS)
-- SPDX-License-Identifier: Apache-2.0
--
-- Generates solidity-step/src/EmulatorConstants.sol
--

local cartesi = require("cartesi")
local util = require("cartesi.util")
local machine = cartesi.machine

local function hex(n) return string.format("0x%x", n) end

local function hex_bytes(s) return cartesi.tohex(s) end

local function reg_addr(name) return machine:get_reg_address(name) end

local UARCH_X_REG_COUNT         = 32
local SHADOW_TLB_SLOT_LOG2_SIZE = 5
local TLB_SET_SIZE              = 256

local SHADOW_TLB_SLOT_SIZE  = 1 << SHADOW_TLB_SLOT_LOG2_SIZE
local SHADOW_TLB_SET_LENGTH = TLB_SET_SIZE * SHADOW_TLB_SLOT_SIZE

assert(
    cartesi.AR_SHADOW_TLB_LENGTH == 3 * SHADOW_TLB_SET_LENGTH,
    "TLB layout drift: AR_SHADOW_TLB_LENGTH != 3 * SHADOW_TLB_SET_LENGTH"
)

local lines = {
"// SPDX-License-Identifier: Apache-2.0",
"pragma solidity ^0.8.30;",
"",
"/// @notice Constants pulled from machine-emulator C++ headers.",
"/// @dev    GENERATED by solidity-step/tools/gen-emulator-constants.lua - do not edit by hand.",
"///         Re-run via `make gen-constants`; CI fails on drift.",
"library EmulatorConstants {",
"    // Address-range geometry (cartesi.AR_*).",
"    uint64 internal constant AR_SHADOW_UARCH_STATE_START = " .. hex(cartesi.AR_SHADOW_UARCH_STATE_START) .. ";",
"    uint64 internal constant AR_UARCH_RAM_START          = " .. hex(cartesi.AR_UARCH_RAM_START) .. ";",
"",
"    // Uarch register init values.",
"    uint64 internal constant UARCH_PC_INIT = AR_UARCH_RAM_START;",
"",
"    // Uarch shadow-state register addresses (cartesi.machine:get_reg_address).",
"    uint64 internal constant UARCH_HALT_ADDR = " .. hex(reg_addr("uarch_halt")) .. ";",
"    uint64 internal constant UARCH_CYCLE_ADDR     = " .. hex(reg_addr("uarch_cycle"))     .. ";",
"    uint64 internal constant UARCH_PC_ADDR        = " .. hex(reg_addr("uarch_pc"))        .. ";",
"    uint64 internal constant UARCH_X_BASE_ADDR    = " .. hex(reg_addr("uarch_x0"))        .. ";",
"",
"    uint8  internal constant UARCH_X_REG_COUNT    = " .. UARCH_X_REG_COUNT .. ";",
"",
"    // Uarch cycle limit (cartesi.UARCH_CYCLE_MAX).",
"    uint64 internal constant UARCH_CYCLE_MAX = " .. cartesi.UARCH_CYCLE_MAX .. ";",
"",
"    // Uarch ECALL function codes (cartesi.UARCH_ECALL_FN_*).",
"    uint64 internal constant UARCH_ECALL_FN_HALT            = " .. cartesi.UARCH_ECALL_FN_HALT .. ";",
"    uint64 internal constant UARCH_ECALL_FN_PUTCHAR         = " .. cartesi.UARCH_ECALL_FN_PUTCHAR .. ";",
"    uint64 internal constant UARCH_ECALL_FN_WRITE_TLB       = " .. cartesi.UARCH_ECALL_FN_WRITE_TLB .. ";",
"",
"    // Uarch state geometry (cartesi.UARCH_STATE_LOG2_SIZE).",
"    uint64 internal constant UARCH_STATE_START_ADDR = AR_SHADOW_UARCH_STATE_START;",
"    uint8  internal constant UARCH_STATE_LOG2_SIZE  = " .. cartesi.UARCH_STATE_LOG2_SIZE .. ";",
"",
"    // Root hash of the pristine uarch state (cartesi.UARCH_PRISTINE_STATE_HASH).",
"    bytes32 internal constant UARCH_PRISTINE_STATE_HASH =",
"        " .. hex_bytes(cartesi.UARCH_PRISTINE_STATE_HASH) .. ";",
"",
"    // Hash tree geometry (cartesi.HASH_TREE_LOG2_*).",
"    uint8 internal constant HASH_TREE_LOG2_WORD_SIZE = " .. cartesi.HASH_TREE_LOG2_WORD_SIZE .. ";",
"    uint8 internal constant HASH_TREE_LOG2_PAGE_SIZE = " .. cartesi.HASH_TREE_LOG2_PAGE_SIZE .. ";",
"    uint8 internal constant HASH_TREE_LOG2_ROOT_SIZE = " .. cartesi.HASH_TREE_LOG2_ROOT_SIZE .. ";",
"",
"    // Step log header hash_function codes (cartesi.HASH_FUNCTION_*). The Solidity",
"    // verifier implements keccak256 only; sha256 is the zkVM path (RISC0).",
"    uint8 internal constant HASH_FUNCTION_KECCAK256 = " .. cartesi.HASH_FUNCTION_KECCAK256 .. ";",
"    uint8 internal constant HASH_FUNCTION_SHA256    = " .. cartesi.HASH_FUNCTION_SHA256 .. ";",
"",
"    // Page geometry (derived).",
"    uint256 internal constant PAGE_SIZE        = 1 << HASH_TREE_LOG2_PAGE_SIZE;",
"    uint64  internal constant PAGE_OFFSET_MASK = (uint64(1) << HASH_TREE_LOG2_PAGE_SIZE) - 1;",
"    uint256 internal constant LEAF_SIZE        = uint256(1) << HASH_TREE_LOG2_WORD_SIZE;",
"",
"    // CMIO buffer geometry (cartesi.AR_CMIO_RX_BUFFER_*).",
"    uint64 internal constant AR_CMIO_RX_BUFFER_START     = " .. hex(cartesi.AR_CMIO_RX_BUFFER_START) .. ";",
"    uint8  internal constant AR_CMIO_RX_BUFFER_LOG2_SIZE = " .. cartesi.AR_CMIO_RX_BUFFER_LOG2_SIZE .. ";",
"",
"    // Shadow TLB layout.",
"    uint64 internal constant AR_SHADOW_TLB_START       = " .. hex(cartesi.AR_SHADOW_TLB_START) .. ";",
"    uint8  internal constant SHADOW_TLB_SLOT_LOG2_SIZE = " .. SHADOW_TLB_SLOT_LOG2_SIZE .. ";",
"    uint64 internal constant SHADOW_TLB_SLOT_SIZE      = uint64(1) << SHADOW_TLB_SLOT_LOG2_SIZE;",
"    uint64 internal constant TLB_SET_SIZE              = " .. TLB_SET_SIZE .. ";",
"    uint64 internal constant SHADOW_TLB_SET_LENGTH     = TLB_SET_SIZE * SHADOW_TLB_SLOT_SIZE;",
"",
"    // Shadow register addresses (cartesi.machine:get_reg_address).",
"    uint64 internal constant IFLAGS_Y_ADDRESS    = " .. hex(reg_addr("iflags_Y"))      .. ";",
"    uint64 internal constant HTIF_TOHOST_ADDRESS = " .. hex(reg_addr("htif_tohost"))   .. ";",
"    uint64 internal constant HTIF_FROMHOST_ADDR  = " .. hex(reg_addr("htif_fromhost")) .. ";",
"    uint64 internal constant MCYCLE_ADDRESS      = " .. hex(reg_addr("mcycle"))        .. ";",
"    uint64 internal constant IMCYCLEMAX_ADDRESS  = " .. hex(reg_addr("imcyclemax"))    .. ";",
"",
"    // Rollup geometry (cartesi.ROLLUP_LOG2_*); bounds the imcyclemax grant per accepted input.",
"    uint32 internal constant ROLLUP_LOG2_MAX_MCYCLES_PER_ADVANCE_STATE = "
    .. cartesi.ROLLUP_LOG2_MAX_MCYCLES_PER_ADVANCE_STATE .. ";",
"",
"    // HTIF tohost field layout [dev:8][cmd:8][reason:16][data:32]; hand-mirrored from htif-constants.hpp.",
"    uint32 internal constant HTIF_DEV_SHIFT    = 0x38;",
"    uint32 internal constant HTIF_CMD_SHIFT    = 0x30;",
"    uint32 internal constant HTIF_REASON_SHIFT = 0x20;",
"    uint64 internal constant HTIF_DEV_MASK     = 0xff00000000000000;",
"    uint64 internal constant HTIF_CMD_MASK     = 0xff000000000000;",
"    uint64 internal constant HTIF_REASON_MASK  = 0xffff00000000;",
"    uint64 internal constant HTIF_DEV_YIELD        = 0x2;",
"    uint64 internal constant HTIF_YIELD_CMD_MANUAL = 0x1;",
"    uint16 internal constant HTIF_YIELD_REASON_ADVANCE_STATE = " .. cartesi.HTIF_YIELD_REASON_ADVANCE_STATE .. ";",
"",
"    // Shadow revert-root-hash slot - protocol-only convention; uarch never touches it.",
"    uint64 internal constant AR_SHADOW_REVERT_ROOT_HASH_START = " .. hex(cartesi.AR_SHADOW_REVERT_ROOT_HASH_START) .. ";",
"",
"    // Manual yield reasons (cartesi.HTIF_YIELD_MANUAL_REASON_*).",
"    uint16 internal constant HTIF_YIELD_MANUAL_REASON_RX_ACCEPTED  = " .. cartesi.HTIF_YIELD_MANUAL_REASON_RX_ACCEPTED .. ";",
"    uint16 internal constant HTIF_YIELD_MANUAL_REASON_RX_REJECTED  = " .. cartesi.HTIF_YIELD_MANUAL_REASON_RX_REJECTED .. ";",
"    uint16 internal constant HTIF_YIELD_MANUAL_REASON_TX_EXCEPTION = " .. cartesi.HTIF_YIELD_MANUAL_REASON_TX_EXCEPTION .. ";",
"",
"    // Step log signature (cartesi.STEP_LOG_SIGNATURE).",
"    bytes8 internal constant STEP_LOG_SIGNATURE = " .. hex_bytes(cartesi.STEP_LOG_SIGNATURE) .. ";",
"}",
""
}

io.write(table.concat(lines, "\n"))
