#!/usr/bin/env lua5.4

-- Copyright Cartesi and individual authors (see AUTHORS)
-- SPDX-License-Identifier: Apache-2.0
--
-- Generates solidity-step/src/EmulatorConstants.sol
--

local cartesi = require("cartesi")
local machine = cartesi.machine

local function hex(n) return string.format("0x%x", n) end

local function hex_bytes(s) return cartesi.tohex(s) end

local function reg_addr(name) return machine:get_reg_address(name) end

local UARCH_X_REG_COUNT         = 32
local SHADOW_TLB_SLOT_LOG2_SIZE = 5
local TLB_SET_SIZE              = 256

local SHADOW_TLB_SLOT_SIZE  = 1 << SHADOW_TLB_SLOT_LOG2_SIZE
local SHADOW_TLB_SET_LENGTH = TLB_SET_SIZE * SHADOW_TLB_SLOT_SIZE

assert(
    cartesi.AR_SHADOW_TLB_LENGTH == 3 * SHADOW_TLB_SET_LENGTH,
    "TLB layout drift: AR_SHADOW_TLB_LENGTH != 3 * SHADOW_TLB_SET_LENGTH"
)

-- Types default to uint64; these pin the narrower types Solidity consumers rely
-- on (assignments do not narrow implicitly).
local TYPE_OVERRIDES = {
    AR_CMIO_RX_BUFFER_LOG2_SIZE = "uint8",
    AR_CMIO_TX_BUFFER_LOG2_SIZE = "uint8",
    HASH_FUNCTION_KECCAK256 = "uint8",
    HASH_FUNCTION_SHA256 = "uint8",
    HASH_TREE_LOG2_PAGE_SIZE = "uint8",
    HASH_TREE_LOG2_ROOT_SIZE = "uint8",
    HASH_TREE_LOG2_WORD_SIZE = "uint8",
    HTIF_CMD_SHIFT = "uint32",
    HTIF_DEV_SHIFT = "uint32",
    HTIF_REASON_SHIFT = "uint32",
    HTIF_YIELD_MANUAL_REASON_RX_ACCEPTED = "uint16",
    HTIF_YIELD_MANUAL_REASON_RX_REJECTED = "uint16",
    HTIF_YIELD_MANUAL_REASON_TX_EXCEPTION = "uint16",
    HTIF_YIELD_REASON_ADVANCE_STATE = "uint16",
    HTIF_YIELD_REASON_INSPECT_STATE = "uint16",
    ROLLUP_LOG2_MAX_MCYCLES_PER_ADVANCE_STATE = "uint32",
    UARCH_STATE_LOG2_SIZE = "uint8",
}

local lines = {
"// SPDX-License-Identifier: Apache-2.0",
"pragma solidity ^0.8.30;",
"",
"/// @notice Constants pulled from machine-emulator C++ headers.",
"/// @dev    GENERATED by solidity-step/tools/gen-emulator-constants.lua - do not edit by hand.",
"///         Re-run via `make gen-constants`; CI fails on drift.",
"library EmulatorConstants {",
"    // Every integer constant exported by the cartesi Lua module, sorted by name.",
}

local names = {}
for name, value in pairs(cartesi) do
    if math.type(value) == "integer" then names[#names + 1] = name end
end
table.sort(names)
for _, name in ipairs(names) do
    local t = TYPE_OVERRIDES[name] or "uint64"
    lines[#lines + 1] = "    " .. t .. " internal constant " .. name .. " = " .. hex(cartesi[name]) .. ";"
end

local tail = {
"",
"    // Uarch register init values.",
"    uint64 internal constant UARCH_PC_INIT = AR_UARCH_RAM_START;",
"",
"    // Uarch shadow-state register addresses (cartesi.machine:get_reg_address).",
"    uint64 internal constant UARCH_HALT_ADDR = " .. hex(reg_addr("uarch_halt")) .. ";",
"    uint64 internal constant UARCH_CYCLE_ADDR     = " .. hex(reg_addr("uarch_cycle"))     .. ";",
"    uint64 internal constant UARCH_PC_ADDR        = " .. hex(reg_addr("uarch_pc"))        .. ";",
"    uint64 internal constant UARCH_X_BASE_ADDR    = " .. hex(reg_addr("uarch_x0"))        .. ";",
"",
"    uint8  internal constant UARCH_X_REG_COUNT    = " .. UARCH_X_REG_COUNT .. ";",
"",
"    // Uarch state geometry.",
"    uint64 internal constant UARCH_STATE_START_ADDR = AR_SHADOW_UARCH_STATE_START;",
"",
"    // Root hash of the pristine uarch state (cartesi.UARCH_PRISTINE_STATE_HASH).",
"    bytes32 internal constant UARCH_PRISTINE_STATE_HASH =",
"        " .. hex_bytes(cartesi.UARCH_PRISTINE_STATE_HASH) .. ";",
"",
"    // Page geometry (derived).",
"    uint256 internal constant PAGE_SIZE        = 1 << HASH_TREE_LOG2_PAGE_SIZE;",
"    uint64  internal constant PAGE_OFFSET_MASK = (uint64(1) << HASH_TREE_LOG2_PAGE_SIZE) - 1;",
"    uint256 internal constant LEAF_SIZE        = uint256(1) << HASH_TREE_LOG2_WORD_SIZE;",
"",
"    // Shadow TLB layout.",
"    uint8  internal constant SHADOW_TLB_SLOT_LOG2_SIZE = " .. SHADOW_TLB_SLOT_LOG2_SIZE .. ";",
"    uint64 internal constant SHADOW_TLB_SLOT_SIZE      = uint64(1) << SHADOW_TLB_SLOT_LOG2_SIZE;",
"    uint64 internal constant TLB_SET_SIZE              = " .. TLB_SET_SIZE .. ";",
"    uint64 internal constant SHADOW_TLB_SET_LENGTH     = TLB_SET_SIZE * SHADOW_TLB_SLOT_SIZE;",
"",
"    // Shadow register addresses (cartesi.machine:get_reg_address).",
"    uint64 internal constant IFLAGS_Y_ADDRESS    = " .. hex(reg_addr("iflags_Y"))      .. ";",
"    uint64 internal constant HTIF_TOHOST_ADDRESS = " .. hex(reg_addr("htif_tohost"))   .. ";",
"    uint64 internal constant HTIF_FROMHOST_ADDR  = " .. hex(reg_addr("htif_fromhost")) .. ";",
"    uint64 internal constant MCYCLE_ADDRESS      = " .. hex(reg_addr("mcycle"))        .. ";",
"    uint64 internal constant IMCYCLEMAX_ADDRESS  = " .. hex(reg_addr("imcyclemax"))    .. ";",
"",
"    // Step log signature (cartesi.STEP_LOG_SIGNATURE).",
"    bytes8 internal constant STEP_LOG_SIGNATURE = " .. hex_bytes(cartesi.STEP_LOG_SIGNATURE) .. ";",
"}",
""
}

for _, l in ipairs(tail) do
    lines[#lines + 1] = l
end

io.write(table.concat(lines, "\n"))
