[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"

fs_permissions = [{ access = "read", path = "../test/fixtures" }]

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
