#!/bin/busybox sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
export HOME=/root
export TERM=vt100

/bin/busybox --install -s

mount -a

ifconfig lo 127.0.0.1

cd $HOME

setsid sh -c 'exec sh < /dev/hvc0 > /dev/hvc0 2>&1'

poweroff -f
