# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cartesi_base_pb2 as cartesi__base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='core.proto',
  package='CartesiCore',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ncore.proto\x12\x0b\x43\x61rtesiCore\x1a\x12\x63\x61rtesi-base.proto2\xb3\x03\n\x07Machine\x12:\n\x03Run\x12\x17.CartesiCore.RunRequest\x1a\x18.CartesiCore.RunResponse\"\x00\x12;\n\x07Machine\x12\x1b.CartesiCore.MachineRequest\x1a\x11.CartesiCore.Void\"\x00\x12\x32\n\x08Snapshot\x12\x11.CartesiCore.Void\x1a\x11.CartesiCore.Void\"\x00\x12\x32\n\x08Rollback\x12\x11.CartesiCore.Void\x1a\x11.CartesiCore.Void\"\x00\x12\x32\n\x08Shutdown\x12\x11.CartesiCore.Void\x1a\x11.CartesiCore.Void\"\x00\x12-\n\x03Inc\x12\x11.CartesiCore.Void\x1a\x11.CartesiCore.Void\"\x00\x12/\n\x05Print\x12\x11.CartesiCore.Void\x1a\x11.CartesiCore.Void\"\x00\x12\x33\n\x04Step\x12\x11.CartesiCore.Void\x1a\x16.CartesiCore.AccessLog\"\x00\x62\x06proto3')
  ,
  dependencies=[cartesi__base__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MACHINE = _descriptor.ServiceDescriptor(
  name='Machine',
  full_name='CartesiCore.Machine',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=48,
  serialized_end=483,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='CartesiCore.Machine.Run',
    index=0,
    containing_service=None,
    input_type=cartesi__base__pb2._RUNREQUEST,
    output_type=cartesi__base__pb2._RUNRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Machine',
    full_name='CartesiCore.Machine.Machine',
    index=1,
    containing_service=None,
    input_type=cartesi__base__pb2._MACHINEREQUEST,
    output_type=cartesi__base__pb2._VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Snapshot',
    full_name='CartesiCore.Machine.Snapshot',
    index=2,
    containing_service=None,
    input_type=cartesi__base__pb2._VOID,
    output_type=cartesi__base__pb2._VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Rollback',
    full_name='CartesiCore.Machine.Rollback',
    index=3,
    containing_service=None,
    input_type=cartesi__base__pb2._VOID,
    output_type=cartesi__base__pb2._VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Shutdown',
    full_name='CartesiCore.Machine.Shutdown',
    index=4,
    containing_service=None,
    input_type=cartesi__base__pb2._VOID,
    output_type=cartesi__base__pb2._VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Inc',
    full_name='CartesiCore.Machine.Inc',
    index=5,
    containing_service=None,
    input_type=cartesi__base__pb2._VOID,
    output_type=cartesi__base__pb2._VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Print',
    full_name='CartesiCore.Machine.Print',
    index=6,
    containing_service=None,
    input_type=cartesi__base__pb2._VOID,
    output_type=cartesi__base__pb2._VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Step',
    full_name='CartesiCore.Machine.Step',
    index=7,
    containing_service=None,
    input_type=cartesi__base__pb2._VOID,
    output_type=cartesi__base__pb2._ACCESSLOG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MACHINE)

DESCRIPTOR.services_by_name['Machine'] = _MACHINE

# @@protoc_insertion_point(module_scope)
