// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.30;

/// @notice Constants pulled from machine-emulator C++ headers.
/// @dev    GENERATED by solidity-step/tools/gen-emulator-constants.lua - do not edit by hand.
///         Re-run via `make gen-constants`; CI fails on drift.
library EmulatorConstants {
    // Every integer constant exported by the cartesi Lua module, sorted by name.
    uint64 internal constant AR_CLINT_LENGTH = 0xc0000;
    uint64 internal constant AR_CLINT_START = 0x2000000;
    uint8 internal constant AR_CMIO_RX_BUFFER_LOG2_SIZE = 0x15;
    uint64 internal constant AR_CMIO_RX_BUFFER_START = 0x60000000;
    uint8 internal constant AR_CMIO_TX_BUFFER_LOG2_SIZE = 0x15;
    uint64 internal constant AR_CMIO_TX_BUFFER_START = 0x60800000;
    uint64 internal constant AR_DTB_LENGTH = 0x100000;
    uint64 internal constant AR_DTB_START = 0x7ff00000;
    uint64 internal constant AR_FIRST_VIRTIO_START = 0x40010000;
    uint64 internal constant AR_HTIF_LENGTH = 0x1000;
    uint64 internal constant AR_HTIF_START = 0x40008000;
    uint64 internal constant AR_LAST_VIRTIO_END = 0x40020000;
    uint64 internal constant AR_PLIC_LENGTH = 0x400000;
    uint64 internal constant AR_PLIC_START = 0x40100000;
    uint64 internal constant AR_PMAS_LENGTH = 0x1000;
    uint64 internal constant AR_PMAS_START = 0x10000;
    uint64 internal constant AR_RAM_START = 0x80000000;
    uint64 internal constant AR_SHADOW_REVERT_ROOT_HASH_START = 0xfe0;
    uint64 internal constant AR_SHADOW_STATE_LENGTH = 0x8000;
    uint64 internal constant AR_SHADOW_STATE_START = 0x0;
    uint64 internal constant AR_SHADOW_TLB_LENGTH = 0x6000;
    uint64 internal constant AR_SHADOW_TLB_START = 0x1000;
    uint64 internal constant AR_SHADOW_UARCH_STATE_LENGTH = 0x1000;
    uint64 internal constant AR_SHADOW_UARCH_STATE_START = 0x400000;
    uint64 internal constant AR_UARCH_RAM_LENGTH = 0x200000;
    uint64 internal constant AR_UARCH_RAM_START = 0x600000;
    uint64 internal constant BREAK_REASON_CONSOLE_INPUT = 0x7;
    uint64 internal constant BREAK_REASON_CONSOLE_OUTPUT = 0x6;
    uint64 internal constant BREAK_REASON_FAILED = 0x0;
    uint64 internal constant BREAK_REASON_HALTED = 0x1;
    uint64 internal constant BREAK_REASON_MCYCLE_OVERFLOW = 0x8;
    uint64 internal constant BREAK_REASON_REACHED_TARGET_MCYCLE = 0x5;
    uint64 internal constant BREAK_REASON_YIELDED_AUTOMATICALLY = 0x3;
    uint64 internal constant BREAK_REASON_YIELDED_MANUALLY = 0x2;
    uint64 internal constant BREAK_REASON_YIELDED_SOFTLY = 0x4;
    uint64 internal constant FLASH_DRIVE_MAX = 0x8;
    uint8 internal constant HASH_FUNCTION_KECCAK256 = 0x0;
    uint8 internal constant HASH_FUNCTION_SHA256 = 0x1;
    uint64 internal constant HASH_SIZE = 0x20;
    uint8 internal constant HASH_TREE_LOG2_PAGE_SIZE = 0xc;
    uint8 internal constant HASH_TREE_LOG2_ROOT_SIZE = 0x40;
    uint8 internal constant HASH_TREE_LOG2_WORD_SIZE = 0x5;
    uint64 internal constant HTIF_CMD_MASK = 0xff000000000000;
    uint32 internal constant HTIF_CMD_SHIFT = 0x30;
    uint64 internal constant HTIF_CONSOLE_CMD_GETCHAR = 0x0;
    uint64 internal constant HTIF_CONSOLE_CMD_GETCHAR_MASK = 0x1;
    uint64 internal constant HTIF_CONSOLE_CMD_PUTCHAR = 0x1;
    uint64 internal constant HTIF_CONSOLE_CMD_PUTCHAR_MASK = 0x2;
    uint64 internal constant HTIF_DATA_MASK = 0xffffffff;
    uint64 internal constant HTIF_DATA_SHIFT = 0x0;
    uint64 internal constant HTIF_DEV_CONSOLE = 0x1;
    uint64 internal constant HTIF_DEV_HALT = 0x0;
    uint64 internal constant HTIF_DEV_MASK = 0xff00000000000000;
    uint32 internal constant HTIF_DEV_SHIFT = 0x38;
    uint64 internal constant HTIF_DEV_YIELD = 0x2;
    uint64 internal constant HTIF_HALT_CMD_HALT = 0x0;
    uint64 internal constant HTIF_HALT_CMD_HALT_MASK = 0x1;
    uint64 internal constant HTIF_REASON_MASK = 0xffff00000000;
    uint32 internal constant HTIF_REASON_SHIFT = 0x20;
    uint64 internal constant HTIF_YIELD_AUTOMATIC_REASON_PROGRESS = 0x1;
    uint64 internal constant HTIF_YIELD_AUTOMATIC_REASON_TX_OUTPUT = 0x2;
    uint64 internal constant HTIF_YIELD_AUTOMATIC_REASON_TX_REPORT = 0x4;
    uint64 internal constant HTIF_YIELD_CMD_AUTOMATIC = 0x0;
    uint64 internal constant HTIF_YIELD_CMD_AUTOMATIC_MASK = 0x1;
    uint64 internal constant HTIF_YIELD_CMD_MANUAL = 0x1;
    uint64 internal constant HTIF_YIELD_CMD_MANUAL_MASK = 0x2;
    uint16 internal constant HTIF_YIELD_MANUAL_REASON_RX_ACCEPTED = 0x1;
    uint16 internal constant HTIF_YIELD_MANUAL_REASON_RX_REJECTED = 0x2;
    uint16 internal constant HTIF_YIELD_MANUAL_REASON_TX_EXCEPTION = 0x4;
    uint16 internal constant HTIF_YIELD_REASON_ADVANCE_STATE = 0x0;
    uint16 internal constant HTIF_YIELD_REASON_INSPECT_STATE = 0x1;
    uint64 internal constant MARCHID = 0x15;
    uint64 internal constant MCYCLE_MAX = 0xffffffffffffffff;
    uint64 internal constant MEMORY_RANGE_LABEL_MAX = 0x1f;
    uint64 internal constant MIMPID = 0x15;
    uint64 internal constant MVENDORID = 0x6361727465736920;
    uint64 internal constant NVRAM_MAX = 0x8;
    uint64 internal constant PMA_CLINT_DID = 0x4;
    uint64 internal constant PMA_CMIO_RX_BUFFER_DID = 0x7;
    uint64 internal constant PMA_CMIO_TX_BUFFER_DID = 0x8;
    uint64 internal constant PMA_EMPTY_DID = 0x0;
    uint64 internal constant PMA_FLASH_DRIVE_DID = 0x3;
    uint64 internal constant PMA_HTIF_DID = 0x5;
    uint64 internal constant PMA_MEMORY_DID = 0x1;
    uint64 internal constant PMA_NVRAM_DID = 0xb;
    uint64 internal constant PMA_PLIC_DID = 0x6;
    uint64 internal constant PMA_SHADOW_STATE_DID = 0x2;
    uint64 internal constant PMA_SHADOW_UARCH_STATE_DID = 0x9;
    uint64 internal constant PMA_VIRTIO_DID = 0xa;
    uint64 internal constant ROLLUP_LOG2_MAX_ADVANCE_STATES_PER_EPOCH = 0x18;
    uint32 internal constant ROLLUP_LOG2_MAX_MCYCLES_PER_ADVANCE_STATE = 0x30;
    uint64 internal constant ROLLUP_LOG2_MAX_OUTPUT_COUNT = 0x3f;
    uint64 internal constant ROLLUP_LOG2_MAX_UARCH_CYCLES_PER_MCYCLE = 0x14;
    uint64 internal constant RTC_FREQ_DIV = 0x2000;
    uint64 internal constant SHARING_ALL = 0x2;
    uint64 internal constant SHARING_CONFIG = 0x1;
    uint64 internal constant SHARING_NONE = 0x0;
    uint64 internal constant UARCH_BREAK_REASON_REACHED_TARGET_UARCH_CYCLE = 0x0;
    uint64 internal constant UARCH_BREAK_REASON_UARCH_CYCLE_OVERFLOW = 0x2;
    uint64 internal constant UARCH_BREAK_REASON_UARCH_HALTED = 0x1;
    uint64 internal constant UARCH_CYCLE_MAX = 0xfffff;
    uint64 internal constant UARCH_ECALL_FN_HALT = 0x1;
    uint64 internal constant UARCH_ECALL_FN_PUTCHAR = 0x2;
    uint64 internal constant UARCH_ECALL_FN_WRITE_TLB = 0x4;
    uint64 internal constant UARCH_RAM_LENGTH = 0x200000;
    uint64 internal constant UARCH_RAM_START_ADDRESS = 0x600000;
    uint64 internal constant UARCH_SHADOW_LENGTH = 0x1000;
    uint64 internal constant UARCH_SHADOW_START_ADDRESS = 0x400000;
    uint8 internal constant UARCH_STATE_LOG2_SIZE = 0x16;
    uint64 internal constant UARCH_STATE_START_ADDRESS = 0x400000;
    uint64 internal constant VERSION_MAJOR = 0x0;
    uint64 internal constant VERSION_MINOR = 0x15;
    uint64 internal constant VERSION_NUM = 0x5208;
    uint64 internal constant VERSION_PATCH = 0x0;

    // Uarch register init values.
    uint64 internal constant UARCH_PC_INIT = AR_UARCH_RAM_START;

    // Uarch shadow-state register addresses (cartesi.machine:get_reg_address).
    uint64 internal constant UARCH_HALT_ADDR = 0x400000;
    uint64 internal constant UARCH_CYCLE_ADDR = 0x400008;
    uint64 internal constant UARCH_PC_ADDR = 0x400010;
    uint64 internal constant UARCH_X_BASE_ADDR = 0x400018;

    uint8 internal constant UARCH_X_REG_COUNT = 32;

    // Uarch state geometry.
    uint64 internal constant UARCH_STATE_START_ADDR = AR_SHADOW_UARCH_STATE_START;

    // Root hash of the pristine uarch state (cartesi.UARCH_PRISTINE_STATE_HASH).
    bytes32 internal constant UARCH_PRISTINE_STATE_HASH =
        0x4260c6a4593287f6e3d75c018d5514db422f8ba34ea7294afb25773e797a98cf;

    // Page geometry (derived).
    uint256 internal constant PAGE_SIZE = 1 << HASH_TREE_LOG2_PAGE_SIZE;
    uint64 internal constant PAGE_OFFSET_MASK = (uint64(1) << HASH_TREE_LOG2_PAGE_SIZE) - 1;
    uint256 internal constant LEAF_SIZE = uint256(1) << HASH_TREE_LOG2_WORD_SIZE;

    // Shadow TLB layout.
    uint8 internal constant SHADOW_TLB_SLOT_LOG2_SIZE = 5;
    uint64 internal constant SHADOW_TLB_SLOT_SIZE = uint64(1) << SHADOW_TLB_SLOT_LOG2_SIZE;
    uint64 internal constant TLB_SET_SIZE = 256;
    uint64 internal constant SHADOW_TLB_SET_LENGTH = TLB_SET_SIZE * SHADOW_TLB_SLOT_SIZE;

    // Shadow register addresses (cartesi.machine:get_reg_address).
    uint64 internal constant IFLAGS_Y_ADDRESS = 0x308;
    uint64 internal constant HTIF_TOHOST_ADDRESS = 0x330;
    uint64 internal constant HTIF_FROMHOST_ADDR = 0x338;
    uint64 internal constant MCYCLE_ADDRESS = 0x100;
    uint64 internal constant IMCYCLEMAX_ADDRESS = 0x2f8;

    // Step log signature (cartesi.STEP_LOG_SIGNATURE).
    bytes8 internal constant STEP_LOG_SIGNATURE = 0x4354534903000000;
}
