-- Shared PRT geometry. The referee uses it to interpret tournaments and the player uses it to
-- construct the corresponding computation hashes.

local cartesi = require("cartesi")

local LOG2_MCYCLES_PER_PERIOD = 10
local MCYCLES_PER_PERIOD = 1 << LOG2_MCYCLES_PER_PERIOD
local UARCH_CYCLES_PER_MCYCLE = 1 << cartesi.ROLLUP_LOG2_MAX_UARCH_CYCLES_PER_MCYCLE
assert(UARCH_CYCLES_PER_MCYCLE - 1 == cartesi.UARCH_CYCLE_MAX, "uarch cycles per mcycle do not match the emulator")

local MCYCLE_HEIGHT = cartesi.ROLLUP_LOG2_MAX_ADVANCE_STATES_PER_EPOCH
    + cartesi.ROLLUP_LOG2_MAX_MCYCLES_PER_ADVANCE_STATE
    - LOG2_MCYCLES_PER_PERIOD
local UARCH_HEIGHT = LOG2_MCYCLES_PER_PERIOD + cartesi.ROLLUP_LOG2_MAX_UARCH_CYCLES_PER_MCYCLE
local PERIODS_PER_INPUT = 1 << (cartesi.ROLLUP_LOG2_MAX_MCYCLES_PER_ADVANCE_STATE - LOG2_MCYCLES_PER_PERIOD)

return {
    LOG2_MCYCLES_PER_PERIOD = LOG2_MCYCLES_PER_PERIOD,
    MCYCLES_PER_PERIOD = MCYCLES_PER_PERIOD,
    UARCH_CYCLES_PER_MCYCLE = UARCH_CYCLES_PER_MCYCLE,
    MCYCLE_HEIGHT = MCYCLE_HEIGHT,
    UARCH_HEIGHT = UARCH_HEIGHT,
    PERIODS_PER_INPUT = PERIODS_PER_INPUT,
}
