#!/usr/bin/env lua5.4
-- Emits the copy-and-patch stencil source (cp-stencils.c) for the backend of
-- copy-patch-rvvm.md.
--
-- The contract is purely positional over the preserve_none argument order
-- (AArch64: x20-x28 then x0-x7, x86-64: r12-r15, rdi, rsi, then more or
-- stack). AArch64 parameters keep the pinned interpreter roster at pc
-- position 4 (x23), countdown 5 (x24), fetch 6 (x25), context 8 (x27).
-- On x86-64 the interpreter's five live arguments occupy positions 1-5;
-- cache slots and context follow in a frame established once per chain.
-- Every stencil passes the complete target-specific roster through.
--
-- Continuations are musttail calls to extern preserve_none symbols (direct
-- branch relocations, patchable, elidable on fallthrough). 64-bit values are
-- addresses of extern hole arrays: movz/movk chains under the AArch64 large
-- code model, movabs under the x86-64 small model with per-symbol large
-- model (clang) or medium model with sized arrays (GCC).
--
-- Usage: lua5.4 cp-gen-stencils.lua <structural.c> <semantic.cpp> [nslots] [arch]
--
-- The structural TU is C, compiled bare-metal (value holes need ELF's
-- movz/movk relocations). The semantic TU is C++, compiled natively with
-- the host toolchain: it includes interpret.cpp so every instruction
-- stencil instantiates the interpreter's own execute body (single
-- semantic source), and its only relocations are continuation branches,
-- which every object format patches.

local out = assert(arg[1], "usage: cp-gen-stencils.lua <structural.c> <semantic.cpp> [nslots] [arch]")
local sem_out = assert(arg[2], "usage: cp-gen-stencils.lua <structural.c> <semantic.cpp> [nslots] [arch]")
local f = assert(io.open(out, "w"))

-- Guest cache slot count; per-host defaults and measurements live in the
-- source Makefile.
local NSLOTS = tonumber(arg[3]) or 7
local arch = arg[4] or "aarch64"

local function emit(s) f:write(s, "\n") end

-- Parameter list. AArch64 retains the pinned roster positions. On x86-64
-- the five live interpreter arguments lead the roster, followed by cache
-- slots and context in the stack half established at chain entry.
local params_t = {}
local args_t = {}
local slot_param
if arch == "x86_64" then
    slot_param = {"sa", "r0", "pc", "cd", "fetch"}
    for d = 1, NSLOTS - 1 do
        slot_param[#slot_param + 1] = ("r%d"):format(d)
    end
    slot_param[#slot_param + 1] = "tcc"
else
    slot_param = {"sa", "r0", "r1", "pc", "cd", "fetch", "r2", "tcc"}
    for d = 3, NSLOTS - 1 do
        slot_param[#slot_param + 1] = ("r%d"):format(d)
    end
end
for _, name in ipairs(slot_param) do
    params_t[#params_t + 1] = "u64 " .. name
    args_t[#args_t + 1] = name
end
local params = table.concat(params_t, ", ")
local args = table.concat(args_t, ", ")

emit("/* Generated by tools/cp-gen-stencils.lua. Do not edit. */")
emit("")
emit("typedef unsigned long long u64;")
emit("typedef long long i64;")
emit("typedef unsigned int u32;")
emit("typedef int i32;")
emit("typedef __int128 i128;")
emit("typedef unsigned __int128 u128;")
emit("#define CONT __attribute__((preserve_none))")
emit("#define TAIL __attribute__((musttail))")
emit("")
emit("/* Continuation holes (patched to branch targets). */")
emit(("CONT extern void cp_cont_0(%s);"):format(params))
emit(("CONT extern void cp_cont_1(%s);"):format(params))
emit("/* 64-bit value holes. */")
emit("#if defined(__x86_64__) && defined(__clang__)")
emit("#define CP_HOLE __attribute__((model(\"large\")))")
emit("#else")
emit("#define CP_HOLE")
emit("#endif")
emit("/* Value-position hole reads must stay 64-bit patchable: on x86 the")
emit(" * compiler may otherwise fold the symbol into a sign-extended imm32")
emit(" * operand (store/cmp/add immediate), which the extractor rejects.")
emit(" * The empty asm pins the value in a register; identity elsewhere. */")
emit("#if defined(__x86_64__)")
emit("static inline u64 cp_v(u64 v) { __asm__(\"\" : \"+r\"(v)); return v; }")
emit("#define CP_VAL(sym) cp_v((u64)(sym))")
emit("#else")
emit("#define CP_VAL(sym) ((u64)(sym))")
emit("#endif")
emit("/* Sized so GCC's medium model (-mlarge-data-threshold) makes them")
emit(" * large data, reached by movabs with R_X86_64_64. */")
emit("CP_HOLE extern char cp_imm64_0[65536];")
emit("CP_HOLE extern char cp_imm64_1[65536];")
emit("CP_HOLE extern char cp_imm64_2[65536];")
emit("CP_HOLE extern char cp_imm64_3[65536];")
emit("")

-- Calls one FP fallback helper without losing the positional roster. The
-- helper address and instruction word are patched per site; success rejoins
-- the generated trace and failure leaves for portable re-execution.
emit("typedef u64 (*cp_fp_helper_t)(u64, u32);")
emit(("CONT void cp_fp_soft(%s)"):format(params))
emit("{")
emit("    cp_fp_helper_t helper = (cp_fp_helper_t)(CP_VAL(cp_imm64_0) + CP_VAL(cp_imm64_2));")
emit("    u64 status = helper(sa, (u32)CP_VAL(cp_imm64_1));")
emit("    if (status != 0) {")
emit("        TAIL return cp_cont_1(" .. args .. ");")
emit("    }")
emit("    TAIL return cp_cont_0(" .. args .. ");")
emit("}")
emit("")

local function fn(name, body)
    emit(("CONT void %s(%s)"):format(name, params))
    emit("{")
    emit(body)
    emit("    TAIL return cp_cont_0(" .. args .. ");")
    emit("}")
    emit("")
end

-- Terminal stencil for the tests: store every parameter through a patched
-- pointer and return to the (ordinary, caller-saves-everything) host caller.
emit(("CONT void cp_store_exit(%s)"):format(params))
emit("{")
emit("    u64 *o = (u64 *)cp_imm64_0;")
for i, name in ipairs(slot_param) do
    emit(("    o[%d] = %s;"):format(i - 1, name))
end
emit("}")
emit("")

-- Trace entry tick guard: the trace body fits before the tick end only when
-- the countdown exceeds the trace's worst-case pending count (a patched
-- constant). Signed compare: the privileged path can drive the countdown
-- negative. Bail is continuation 1, the body is the elidable fallthrough.
emit(("CONT void cp_tick_guard(%s)"):format(params))
emit("{")
emit("    if ((i64)cd <= (i64)CP_VAL(cp_imm64_0)) {")
emit("        TAIL return cp_cont_1(" .. args .. ");")
emit("    }")
emit("    TAIL return cp_cont_0(" .. args .. ");")
emit("}")
emit("")

-- Side exit: move the fast pc by a signed delta from the trace head
-- (the typed fast pc is position-encoded, so exits add displacements,
-- never absolute values), charge the pending instruction count against
-- the countdown, and leave for the fetch-tail continuation.
emit(("CONT void cp_exit_stub(%s)"):format(params))
emit("{")
emit("    pc += CP_VAL(cp_imm64_0);")
emit("    cd -= CP_VAL(cp_imm64_1);")
emit("    TAIL return cp_cont_0(" .. args .. ");")
emit("}")
emit("")

-- Compare a 64-bit field at a patched address against a patched constant,
-- bailing on mismatch. The call-entry prologue validates the translation
-- context and the hot code-TLB slot with these; the bail leaves with the
-- caller's deposit pc untouched, so misses resume the ordinary fetch path.
emit(("CONT void cp_cmp_mem_imm(%s)"):format(params))
emit("{")
emit("    if (*(u64 *)cp_imm64_0 != CP_VAL(cp_imm64_1)) {")
emit("        TAIL return cp_cont_1(" .. args .. ");")
emit("    }")
emit("    TAIL return cp_cont_0(" .. args .. ");")
emit("}")
emit("")

-- Copy a 64-bit field between two patched addresses (the entry-time
-- pma_index publish, read from the shadow slot).
emit(("CONT void cp_copy_mem(%s)"):format(params))
emit("{")
emit("    *(u64 *)cp_imm64_1 = *(u64 *)cp_imm64_0;")
emit("    TAIL return cp_cont_0(" .. args .. ");")
emit("}")
emit("")

-- Bail-path counter: bump a 64-bit counter through a patched address.
-- Emitted only on cold paths (the per-cause counting islands), so the
-- statistics cost nothing on hot paths.
emit(("CONT void cp_count(%s)"):format(params))
emit("{")
emit("    ++*(u64 *)cp_imm64_0;")
emit("    TAIL return cp_cont_0(" .. args .. ");")
emit("}")
emit("")

-- Fused call prologue, stencil one: probe the hot code-TLB slot of the
-- current translation context (exactly the interpreter's per-transit fetch
-- probe; content identity comes from the vh compare), then
-- establish: pc derives
-- from the incoming deposit (vpc + caller vf, the universal entry
-- convention) without a hole, the fetch register and penumbra vf publish
-- the recorded mapping, and the computed slot index rides to stencil two
-- in slot r0 (dead at entry). Holes: 0 hot-set base, 1 head page, 2
-- recorded vf, 3 the tlb_ctx_slot_base address. Layout facts baked as
-- literals (slot sizes, the vf-next-to-ctx adjacency, the tcc field
-- offsets) are pinned by static_asserts in interpret-cp.inc.
local TCC_FETCH_PAGE_OFF = 32
local TCC_PMA_OFF = 40
emit(("CONT void cp_call_probe(%s)"):format(params))
emit("{")
emit("    u64 idx = (((u64)cp_imm64_1) >> 12) & 255;")
emit("    u64 ctxb = *(u64 *)cp_imm64_3;")
emit("    u64 *slot = (u64 *)((u64)cp_imm64_0 + (ctxb + idx) * 16);")
emit("    if (slot[0] != CP_VAL(cp_imm64_1) || slot[1] != CP_VAL(cp_imm64_2)) {")
emit("        TAIL return cp_cont_1(" .. args .. ");")
emit("    }")
emit("    u64 caller_vf = *(u64 *)((u64)cp_imm64_3 - 8);")
emit("    pc = pc - caller_vf + CP_VAL(cp_imm64_2);")
emit("    *(u64 *)((u64)cp_imm64_3 - 8) = CP_VAL(cp_imm64_2);")
emit("    fetch = CP_VAL(cp_imm64_1) + CP_VAL(cp_imm64_2);")
emit(("    *(u64 *)(tcc + %d) = fetch;"):format(TCC_FETCH_PAGE_OFF))
emit("    r0 = ctxb + idx;")
emit("    TAIL return cp_cont_0(" .. args .. ");")
emit("}")
emit("")
-- Stencil two: the entry-time pma publish from the shadow slot of the
-- same (current-context) index, delivered in r0. Hole: 0 shadow-set base.
emit(("CONT void cp_call_pma(%s)"):format(params))
emit("{")
emit("    u64 pma = *(u64 *)((u64)cp_imm64_0 + r0 * 32 + 16);")
emit(("    *(u64 *)(tcc + %d) = pma;"):format(TCC_PMA_OFF))
emit("    TAIL return cp_cont_0(" .. args .. ");")
emit("}")
emit("")

-- Store a patched constant through a patched address. The call-entry
-- prologue publishes the established fetch-mapping fields with these,
-- before the register re-encode, with no C boundary in between.
emit(("CONT void cp_store_imm(%s)"):format(params))
emit("{")
emit("    *(u64 *)cp_imm64_0 = CP_VAL(cp_imm64_1);")
emit("    TAIL return cp_cont_0(" .. args .. ");")
emit("}")
emit("")

-- Call-entry establishment: re-encode the pinned pc and fetch registers to
-- the trace's recorded mapping. Both are install-time constants because the
-- hook only enters when the hot slot's vh_offset equals the recorded
-- code_vf_offset. Falls through into the tick guard.
emit(("CONT void cp_call_establish(%s)"):format(params))
emit("{")
emit("    pc = CP_VAL(cp_imm64_0);")
emit("    fetch = CP_VAL(cp_imm64_1);")
emit("    TAIL return cp_cont_0(" .. args .. ");")
emit("}")
emit("")

-- li: slot d = constant.
for d = 0, NSLOTS - 1 do
    fn(("cp_li_%d"):format(d), ("    r%d = CP_VAL(cp_imm64_0);"):format(d))
end

-- Far jump: tail call through a 64-bit hole, the per-heap island through
-- which exits reach the interpreter continuation beyond direct branch
-- range. No runtime assembler: the indirect branch is compiler-emitted.
emit(("typedef CONT void (*cp_cont_t)(%s);"):format(params))
emit(("CONT void cp_far_jump(%s)"):format(params))
emit("{")
emit("    /* Two-hole sum defeats the direct-branch fold: the compiler")
emit("     * cannot resolve sym+sym to one target, so it materializes and")
emit("     * branches through a register. Patched as target plus zero. */")
emit("    TAIL return ((cp_cont_t)(CP_VAL(cp_imm64_0) + CP_VAL(cp_imm64_1)))(" .. args .. ");")
emit("}")
emit("")

-- Dynamic-exit deposit: re-encode the pinned pc as the interpreter's own
-- convention for an indirect target, vaddr plus the current segment's
-- fetch_vf_offset (loaded through the patched address). Runs after the
-- countdown charge, before the lookup: both the chain hit and every miss
-- or bail leave with this exact deposit, as execute_jump would.
for d = 0, NSLOTS - 1 do
    fn(("cp_deposit_pc_%d"):format(d), ("    pc = r%d + *(u64 *)cp_imm64_0;"):format(d))
end

-- Lookup tail (RVVM jtlb probe): direct-mapped front cache of
-- {guest vpc, self-validating call entry} pairs, indexed (v >> 1) & mask.
-- A hit chains straight into the entry (which validates and, on any
-- mismatch, bails to the island with the deposit pc); a miss leaves for
-- the island. The cold paths all stay behind exits.
for d = 0, NSLOTS - 1 do
    emit(("CONT void cp_lookup_%d(%s)"):format(d, params))
    emit("{")
    emit(("    u64 v = r%d;"):format(d))
    emit("    u64 *e = (u64 *)((u64)cp_imm64_0 + (((v >> 1) & 255) << 4));")
    emit("    if (e[0] == v) {")
    emit("        TAIL return ((cp_cont_t)e[1])(" .. args .. ");")
    emit("    }")
    emit("    TAIL return cp_cont_0(" .. args .. ");")
    emit("}")
    emit("")
end

f:close()

-- Semantic TU: wrappers instantiating the interpreter's execute bodies.
local g = assert(io.open(sem_out, "w"))
local function gem(line) g:write(line, "\n") end

gem("/* Generated by tools/cp-gen-stencils.lua. Do not edit. */")
gem("// NOLINTBEGIN")
gem("#define TC_TRANSLATION_UNIT")
gem('#include "interpret.cpp"')
gem("")
gem("namespace cartesi {")
gem("struct cp_slot_access;")
gem("template <>")
gem("struct i_state_access_fast_addr<cp_slot_access> {")
gem("    using type = uint64_t;")
gem("};")
gem("// Binds the synthetic instruction's rs1=1, rs2=2, rd=3 to wrapper")
gem("// locals, so each execute body folds onto the placement's registers.")
gem("struct cp_slot_access : i_state_access<cp_slot_access>, i_accept_scoped_notes<cp_slot_access> {")
gem("    uint64_t *v1;")
gem("    uint64_t *v2;")
gem("    uint64_t *vd;")
gem("    cp_slot_access(uint64_t *a1, uint64_t *a2, uint64_t *ad) : v1(a1), v2(a2), vd(ad) {}")
gem("    static const char *do_get_name() {")
gem('        return "cp_slot_access";')
gem("    }")
gem("    uint64_t do_read_x(int i) const {")
gem("        return i == 1 ? *v1 : *v2;")
gem("    }")
gem("    void do_write_x(int /*i*/, uint64_t val) const {")
gem("        *vd = val;")
gem("    }")
gem("    // Exception-path surface instantiated by the branch bodies; dead")
gem("    // under the aligned synthetic offset and folded away, never run.")
gem("    static uint64_t do_read_iprv() { return 0; }")
gem("    static void do_write_iprv(uint64_t) {}")
gem("    static uint64_t do_read_medeleg() { return 0; }")
gem("    static uint64_t do_read_mideleg() { return 0; }")
gem("    static uint64_t do_read_mstatus() { return 0; }")
gem("    static void do_write_mstatus(uint64_t) {}")
gem("    static uint64_t do_read_mtvec() { return 0; }")
gem("    static uint64_t do_read_stvec() { return 0; }")
gem("    static uint64_t do_read_icycleinstret() { return 0; }")
gem("    static void do_write_icycleinstret(uint64_t) {}")
gem("    static void do_write_ilrsc(uint64_t) {}")
gem("    static void do_write_mcause(uint64_t) {}")
gem("    static void do_write_mepc(uint64_t) {}")
gem("    static void do_write_mtval(uint64_t) {}")
gem("    static void do_write_scause(uint64_t) {}")
gem("    static void do_write_sepc(uint64_t) {}")
gem("    static void do_write_stval(uint64_t) {}")
gem("    static uint64_t do_read_fetch_vf_offset() { return 0; }")
gem("};")
gem("")
gem("// Memory-op accessor: slots for the register file, everything else")
gem("// forwarded to the real state access reconstructed from the sa")
gem("// parameter, so the emitted probe is the committed hot TLB path")
gem("// against the emulator's own layout. The slow path is intercepted")
gem("// below and turned into a bail.")
gem("struct cp_mem_access;")
gem("template <>")
gem("struct i_state_access_fast_addr<cp_mem_access> {")
gem("    using type = uint64_t;")
gem("};")
gem("struct cp_mem_access : i_state_access<cp_mem_access>, i_accept_scoped_notes<cp_mem_access> {")
gem("    state_access s;")
gem("    uint64_t *v1;")
gem("    uint64_t *v2;")
gem("    uint64_t *vd;")
gem("    uint64_t ctx_slot_base;")
gem("    static_assert(sizeof(state_access) == sizeof(uint64_t));")
gem("    cp_mem_access(uint64_t sa_bits, uint64_t *a1, uint64_t *a2, uint64_t *ad, uint64_t ctxb)")
gem("        : s(std::bit_cast<state_access>(sa_bits)), v1(a1), v2(a2), vd(ad), ctx_slot_base(ctxb) {}")
gem("    static const char *do_get_name() {")
gem('        return "cp_mem_access";')
gem("    }")
gem("    uint64_t do_read_x(int i) const {")
gem("        return i == 1 ? *v1 : *v2;")
gem("    }")
gem("    void do_write_x(int /*i*/, uint64_t val) const {")
gem("        *vd = val;")
gem("    }")
gem("    uint64_t do_read_tlb_ctx_slot_base() const {")
gem("        return ctx_slot_base;")
gem("    }")
gem("    template <TLB_set_index E>")
gem("    uint64_t do_read_tlb_vaddr_page(uint64_t i) const {")
gem("        return static_cast<uint64_t>(s.template read_tlb_vaddr_page<E>(i));")
gem("    }")
gem("    // Lazy hot-slot init is an out-of-line cold member; in the")
gem("    // hit-or-bail shape an uninitialized slot stays a miss and the")
gem("    // interpreter initializes it portably after the bail.")
gem("    template <TLB_set_index E>")
gem("    uint64_t do_init_hot_tlb_slot(uint64_t i) const {")
gem("        return static_cast<uint64_t>(s.template read_tlb_vaddr_page<E>(i));")
gem("    }")
gem("    template <TLB_set_index E>")
gem("    bool do_verify_cold_tlb_slot(uint64_t i) const {")
gem("        return s.template verify_cold_tlb_slot<E>(i);")
gem("    }")
gem("    template <TLB_set_index E>")
gem("    uint64_t do_read_tlb_pma_index(uint64_t i) const {")
gem("        return s.template read_tlb_pma_index<E>(i);")
gem("    }")
gem("    template <TLB_set_index E>")
gem("    uint64_t do_read_tlb_vf_offset(uint64_t i) const {")
gem("        return static_cast<uint64_t>(s.template read_tlb_vf_offset<E>(i));")
gem("    }")
gem("    template <typename T, typename A>")
gem("    void do_read_memory_word(uint64_t faddr, uint64_t pma_index, T *pval) const {")
gem("        s.template read_memory_word<T, A>(host_addr{faddr}, pma_index, pval);")
gem("    }")
gem("    template <typename T, typename A>")
gem("    void do_write_memory_word(uint64_t faddr, uint64_t pma_index, T val) const {")
gem("        s.template write_memory_word<T, A>(host_addr{faddr}, pma_index, val);")
gem("    }")
gem("    // Exception-path surface, forwarded to the real accessor: correct")
gem("    // if reachable, dead under the intercepted slow path otherwise.")
for _, csr in ipairs({ "icycleinstret", "mstatus", "iprv", "mcause", "mepc", "mtval", "scause", "sepc",
    "stval" }) do
    gem(("    uint64_t do_read_%s() const {"):format(csr))
    gem(("        return s.read_%s();"):format(csr))
    gem("    }")
    gem(("    void do_write_%s(uint64_t val) const {"):format(csr))
    gem(("        s.write_%s(val);"):format(csr))
    gem("    }")
end
for _, csr in ipairs({ "medeleg", "mideleg", "mtvec", "stvec" }) do
    gem(("    uint64_t do_read_%s() const {"):format(csr))
    gem(("        return s.read_%s();"):format(csr))
    gem("    }")
end
gem("    void do_write_ilrsc(uint64_t val) const {")
gem("        s.write_ilrsc(val);")
gem("    }")
gem("    // CSR accessor surface: the instantiated read_csr/write_csr")
gem("    // switches reference every CSR even though the baked index")
gem("    // folds all but one branch away after instantiation.")
gem("    uint64_t do_read_fcsr() const {")
gem("        return s.read_fcsr();")
gem("    }")
gem("    uint64_t do_read_marchid() const {")
gem("        return s.read_marchid();")
gem("    }")
gem("    uint64_t do_read_mcounteren() const {")
gem("        return s.read_mcounteren();")
gem("    }")
gem("    uint64_t do_read_menvcfg() const {")
gem("        return s.read_menvcfg();")
gem("    }")
gem("    uint64_t do_read_mie() const {")
gem("        return s.read_mie();")
gem("    }")
gem("    uint64_t do_read_mimpid() const {")
gem("        return s.read_mimpid();")
gem("    }")
gem("    uint64_t do_read_mip() const {")
gem("        return s.read_mip();")
gem("    }")
gem("    uint64_t do_read_misa() const {")
gem("        return s.read_misa();")
gem("    }")
gem("    uint64_t do_read_mscratch() const {")
gem("        return s.read_mscratch();")
gem("    }")
gem("    uint64_t do_read_mvendorid() const {")
gem("        return s.read_mvendorid();")
gem("    }")
gem("    uint64_t do_read_satp() const {")
gem("        return s.read_satp();")
gem("    }")
gem("    uint64_t do_read_scounteren() const {")
gem("        return s.read_scounteren();")
gem("    }")
gem("    uint64_t do_read_senvcfg() const {")
gem("        return s.read_senvcfg();")
gem("    }")
gem("    uint64_t do_read_sscratch() const {")
gem("        return s.read_sscratch();")
gem("    }")
gem("    void do_write_fcsr(uint64_t val) const {")
gem("        s.write_fcsr(val);")
gem("    }")
gem("    void do_write_mie(uint64_t val) const {")
gem("        s.write_mie(val);")
gem("    }")
gem("    void do_write_scounteren(uint64_t val) const {")
gem("        s.write_scounteren(val);")
gem("    }")
gem("    void do_write_senvcfg(uint64_t val) const {")
gem("        s.write_senvcfg(val);")
gem("    }")
gem("    void do_write_stvec(uint64_t val) const {")
gem("        s.write_stvec(val);")
gem("    }")
gem("    void do_write_mcounteren(uint64_t val) const {")
gem("        s.write_mcounteren(val);")
gem("    }")
gem("    void do_write_medeleg(uint64_t val) const {")
gem("        s.write_medeleg(val);")
gem("    }")
gem("    void do_write_menvcfg(uint64_t val) const {")
gem("        s.write_menvcfg(val);")
gem("    }")
gem("    void do_write_mideleg(uint64_t val) const {")
gem("        s.write_mideleg(val);")
gem("    }")
gem("    void do_write_mip(uint64_t val) const {")
gem("        s.write_mip(val);")
gem("    }")
gem("    void do_write_mscratch(uint64_t val) const {")
gem("        s.write_mscratch(val);")
gem("    }")
gem("    void do_write_mtvec(uint64_t val) const {")
gem("        s.write_mtvec(val);")
gem("    }")
gem("    void do_write_satp(uint64_t val) const {")
gem("        s.write_satp(val);")
gem("    }")
gem("    void do_write_sscratch(uint64_t val) const {")
gem("        s.write_sscratch(val);")
gem("    }")
gem("    // Referenced by the satp/mstatus write paths, dead in every")
gem("    // instantiated wrapper (the baked CSR index folds those away).")
gem("    template <TLB_set_index SET>")
gem("    void do_write_tlb(uint64_t slot_index, uint64_t vaddr_page, uint64_t vh_offset, uint64_t pma_index) const {")
gem("        s.template write_tlb<SET>(slot_index, vaddr_page, host_addr{vh_offset}, pma_index);")
gem("    }")
gem("};")
gem("")
gem("// Slow-path interception: found by argument-dependent lookup at the")
gem("// instantiation of read/write_virtual_memory for cp_mem_access and")
gem("// preferred by partial ordering. Mutates nothing and reports failure,")
gem("// so the wrapper bails and the interpreter re-executes the")
gem("// instruction portably, running the true slow path there.")
gem("template <typename>")
gem("inline constexpr bool is_cp_mem_access = false;")
gem("template <>")
gem("inline constexpr bool is_cp_mem_access<cp_mem_access> = true;")
gem("template <typename T, typename STATE_ACCESS, bool RAISE_STORE_EXCEPTIONS = false>")
gem("    requires(is_cp_mem_access<STATE_ACCESS>)")
gem("static FORCE_INLINE std::pair<bool, uint64_t> read_virtual_memory_slow(const STATE_ACCESS /*a*/, uint64_t pc,")
gem("    uint64_t /*mcycle*/, uint64_t /*vaddr*/, T * /*pval*/) {")
gem("    return {false, pc};")
gem("}")
gem("template <typename T, typename STATE_ACCESS>")
gem("    requires(is_cp_mem_access<STATE_ACCESS>)")
gem("static FORCE_INLINE std::pair<execute_status, uint64_t> write_virtual_memory_slow(const STATE_ACCESS /*a*/,")
gem("    uint64_t pc, uint64_t /*mcycle*/, uint64_t /*vaddr*/, uint64_t /*val64*/) {")
gem("    return {execute_status::failure, pc};")
gem("}")
gem("// Narrowed CSR dispatch for the wrappers: only the three FP CSRs the")
gem("// selection bakes are reachable, dispatched straight to the")
gem("// interpreter's own per-CSR helpers (semantics stay single-source);")
gem("// anything else reports failure and the wrapper bails. This also")
gem("// keeps the whole path inlinable, which the full read_csr/write_csr")
gem("// switches are not.")
gem("template <typename STATE_ACCESS>")
gem("    requires(is_cp_mem_access<STATE_ACCESS>)")
gem("static FORCE_INLINE uint64_t read_csr(const STATE_ACCESS a, uint64_t /*mcycle*/, CSR_address csraddr,")
gem("    bool *status) {")
gem("    switch (csraddr) {")
gem("        case CSR_address::fflags:")
gem("            return read_csr_fflags(a, status);")
gem("        case CSR_address::frm:")
gem("            return read_csr_frm(a, status);")
gem("        case CSR_address::fcsr:")
gem("            return read_csr_fcsr(a, status);")
gem("        default:")
gem("            *status = false;")
gem("            return 0;")
gem("    }")
gem("}")
gem("template <typename STATE_ACCESS>")
gem("    requires(is_cp_mem_access<STATE_ACCESS>)")
gem("static FORCE_INLINE execute_status write_csr(const STATE_ACCESS a, uint64_t /*mcycle*/, CSR_address csraddr,")
gem("    uint64_t val) {")
gem("    switch (csraddr) {")
gem("        case CSR_address::fflags:")
gem("            return write_csr_fflags(a, val);")
gem("        case CSR_address::frm:")
gem("            return write_csr_frm(a, val);")
gem("        case CSR_address::fcsr:")
gem("            return write_csr_fcsr(a, val);")
gem("        default:")
gem("            return execute_status::failure;")
gem("    }")
gem("}")
gem("// Same interception for the illegal-instruction raise: a CSR body's")
gem("// only failure (FS off for the FP CSRs) must bail to the interpreter,")
gem("// which re-executes the instruction and raises architecturally.")
gem("template <typename STATE_ACCESS>")
gem("    requires(is_cp_mem_access<STATE_ACCESS>)")
gem("static FORCE_INLINE execute_status raise_illegal_insn_exception(const STATE_ACCESS /*a*/, uint64_t & /*pc*/,")
gem("    uint32_t /*insn*/) {")
gem("    return execute_status::failure;")
gem("}")
gem("} // namespace cartesi")
gem("")
gem("typedef unsigned long long u64;")
gem("#define CONT __attribute__((preserve_none))")
gem("#define TAIL __attribute__((musttail))")
gem(("extern \"C\" CONT void cp_cont_0(%s);"):format(params))
gem(("extern \"C\" CONT void cp_cont_1(%s);"):format(params))
gem("")

local function sem_sorted(t)
    local names = {}
    for name in pairs(t) do
        names[#names + 1] = name
    end
    table.sort(names)
    return names
end

-- Raw floating-register transfers. FP values use transient roster slots;
-- unlike the integer cache they are written back within the instruction.
for slot = 0, NSLOTS - 1 do
    for reg = 0, 31 do
        gem(("extern \"C\" CONT void cp_fxl_%d_%d(%s)"):format(slot, reg, params))
        gem("{")
        gem("    const auto acc = std::bit_cast<cartesi::state_access>(sa);")
        gem(("    r%d = acc.read_f(%d);"):format(slot, reg))
        gem("    TAIL return cp_cont_0(" .. args .. ");")
        gem("}")
        gem("")
        gem(("extern \"C\" CONT void cp_fxs_%d_%d(%s)"):format(slot, reg, params))
        gem("{")
        gem("    const auto acc = std::bit_cast<cartesi::state_access>(sa);")
        gem(("    acc.write_f(%d, r%d);"):format(reg, slot))
        gem("    TAIL return cp_cont_0(" .. args .. ");")
        gem("}")
        gem("")
    end
end

-- Exact FP operations share one architectural guard. Their operation
-- stencils use only integer/soft-float bit semantics: there is no host-FPU
-- attempt and no soft-only fallback continuation.
gem(("extern \"C\" CONT void cp_fp_fs_guard(%s)"):format(params))
gem("{")
gem("    const auto acc = std::bit_cast<cartesi::state_access>(sa);")
gem("    if ((acc.read_mstatus() & cartesi::MSTATUS_FS_MASK) == cartesi::MSTATUS_FS_OFF) {")
gem("        TAIL return cp_cont_1(" .. args .. ");")
gem("    }")
gem("    TAIL return cp_cont_0(" .. args .. ");")
gem("}")
gem("")

gem(("extern \"C\" CONT void cp_fp_always_soft(%s)"):format(params))
gem("{")
gem("    TAIL return cp_cont_1(" .. args .. ");")
gem("}")
gem("")

local FP_EXACT_BINARY = {
    fsgnj = "(a & ~SIGN) | (b & SIGN)",
    fsgnjn = "(a & ~SIGN) | ((b & SIGN) ^ SIGN)",
    fsgnjx = "a ^ (b & SIGN)",
}
for _, width in ipairs({ "s", "d" }) do
    local uint = width == "s" and "uint32_t" or "uint64_t"
    local iface = width == "s" and "i_sfloat32" or "i_sfloat64"
    local boxed = width == "s" and "cartesi::float_box(result)" or "result"
    for _, opname in ipairs(sem_sorted(FP_EXACT_BINARY)) do
        for d = 0, NSLOTS - 1 do
            for s = 0, NSLOTS - 1 do
                gem(("extern \"C\" CONT void cp_fp_%s_%s_%d_%d(%s)"):format(opname, width, d, s, params))
                gem("{")
                gem(("    constexpr %s SIGN = cartesi::%s::SIGN_MASK;"):format(uint, iface))
                gem(("    const %s a = cartesi::float_unbox<%s>(r%d);"):format(uint, uint, d))
                gem(("    const %s b = cartesi::float_unbox<%s>(r%d);"):format(uint, uint, s))
                gem(("    const %s result = %s;"):format(uint, FP_EXACT_BINARY[opname]))
                gem(("    r%d = %s;"):format(d, boxed))
                gem("    TAIL return cp_cont_0(" .. args .. ");")
                gem("}")
                gem("")
            end
        end
    end
    for _, opname in ipairs({ "min", "max" }) do
        for d = 0, NSLOTS - 1 do
            for s = 0, NSLOTS - 1 do
                gem(("extern \"C\" CONT void cp_fp_%s_%s_%d_%d(%s)"):format(opname, width, d, s, params))
                gem("{")
                gem("    const auto acc = std::bit_cast<cartesi::state_access>(sa);")
                gem("    const uint64_t fcsr = acc.read_fcsr();")
                gem("    uint32_t fflags = cartesi::fcsr_fflags(fcsr);")
                gem(("    const %s a = cartesi::float_unbox<%s>(r%d);"):format(uint, uint, d))
                gem(("    const %s b = cartesi::float_unbox<%s>(r%d);"):format(uint, uint, s))
                gem(("    const %s result = cartesi::%s::%s_exact(a, b, &fflags);"):format(uint, iface, opname))
                gem(("    r%d = %s;"):format(d, boxed))
                gem("    acc.write_fcsr((fcsr & ~cartesi::FCSR_FFLAGS_RW_MASK) | fflags);")
                gem("    TAIL return cp_cont_0(" .. args .. ");")
                gem("}")
                gem("")
            end
        end
    end
    for _, opname in ipairs({ "eq", "le", "lt" }) do
        for d = 0, NSLOTS - 1 do
            for s = 0, NSLOTS - 1 do
                gem(("extern \"C\" CONT void cp_fp_%s_%s_%d_%d(%s)"):format(opname, width, d, s, params))
                gem("{")
                gem("    const auto acc = std::bit_cast<cartesi::state_access>(sa);")
                gem("    const uint64_t fcsr = acc.read_fcsr();")
                gem("    uint32_t fflags = cartesi::fcsr_fflags(fcsr);")
                gem(("    const %s a = cartesi::float_unbox<%s>(r%d);"):format(uint, uint, d))
                gem(("    const %s b = cartesi::float_unbox<%s>(r%d);"):format(uint, uint, s))
                gem(("    r%d = cartesi::%s::%s_exact(a, b, &fflags);"):format(d, iface, opname))
                gem("    acc.write_fcsr((fcsr & ~cartesi::FCSR_FFLAGS_RW_MASK) | fflags);")
                gem("    TAIL return cp_cont_0(" .. args .. ");")
                gem("}")
                gem("")
            end
        end
    end
    for d = 0, NSLOTS - 1 do
        gem(("extern \"C\" CONT void cp_fp_class_%s_%d(%s)"):format(width, d, params))
        gem("{")
        gem(("    r%d = cartesi::%s::fclass_exact(cartesi::float_unbox<%s>(r%d));"):format(d, iface, uint, d))
        gem("    TAIL return cp_cont_0(" .. args .. ");")
        gem("}")
        gem("")
    end
end

-- Guarded host-FPU binary arithmetic. The hard-float proof is reused
-- directly: RNE (static or dynamically resolved), sticky NX, boxed singles,
-- zero-or-normal operands, and a strictly-normal result. A miss touches no
-- guest state and takes continuation 1 to the soft-only instruction body.
local FP_BIN_OPS = {
    add = "+",
    sub = "-",
    mul = "*",
    div = "/",
}
for _, width in ipairs({ "s", "d" }) do
    local uint = width == "s" and "uint32_t" or "uint64_t"
    local host = width == "s" and "float" or "double"
    local iface = width == "s" and "i_float32" or "i_float64"
    local boxed_mask = width == "s" and "UINT64_C(0xffffffff00000000)" or "UINT64_C(0)"
    for _, dynamic in ipairs({ false, true }) do
        local mode = dynamic and "dyn" or "rne"
        for _, opname in ipairs(sem_sorted(FP_BIN_OPS)) do
            local op = FP_BIN_OPS[opname]
            for d = 0, NSLOTS - 1 do
                for s = 0, NSLOTS - 1 do
                    gem(("extern \"C\" CONT void cp_fp_%s_%s_%s_%d_%d(%s)"):format(opname, width, mode, d, s, params))
                    gem("{")
                    gem("#ifdef HARD_FLOAT")
                    gem("    const auto acc = std::bit_cast<cartesi::state_access>(sa);")
                    gem("    const uint64_t fcsr = acc.read_fcsr();")
                    gem("    if ((acc.read_mstatus() & cartesi::MSTATUS_FS_MASK) == cartesi::MSTATUS_FS_OFF) {")
                    gem("        TAIL return cp_cont_1(" .. args .. ");")
                    gem("    }")
                    if dynamic then
                        gem("    if (((fcsr >> cartesi::FCSR_FRM_SHIFT) & 7) != cartesi::FRM_RNE) {")
                        gem("        TAIL return cp_cont_1(" .. args .. ");")
                        gem("    }")
                    end
                    if width == "s" then
                        gem(("    if ((r%d & %s) != %s || (r%d & %s) != %s) {"):format(d, boxed_mask, boxed_mask,
                            s, boxed_mask, boxed_mask))
                        gem("        TAIL return cp_cont_1(" .. args .. ");")
                        gem("    }")
                    end
                    gem(("    const %s a = static_cast<%s>(r%d);"):format(uint, uint, d))
                    gem(("    const %s b = static_cast<%s>(r%d);"):format(uint, uint, s))
                    gem(("    if (acc.get_penumbra().hard_float_enabled == 0 ||"):format())
                    gem("        (cartesi::fcsr_fflags(fcsr) & cartesi::FFLAGS_NX_MASK) == 0 ||")
                    gem(("        !cartesi::%s::is_zero_or_normal(a) || !cartesi::%s::is_zero_or_normal(b)) {"):format(
                        iface, iface))
                    gem("        TAIL return cp_cont_1(" .. args .. ");")
                    gem("    }")
                    gem(
                        ("    const %s result = std::bit_cast<%s>(" ..
                            "std::bit_cast<%s>(a) %s std::bit_cast<%s>(b));"):format(uint, uint, host, op, host))
                    gem(("    if (!cartesi::%s::is_safe_result(result)) {"):format(iface))
                    gem("        TAIL return cp_cont_1(" .. args .. ");")
                    gem("    }")
                    if width == "s" then
                        gem(("    r%d = static_cast<uint64_t>(result) | %s;"):format(d, boxed_mask))
                    else
                        gem(("    r%d = result;"):format(d))
                    end
                    gem("    TAIL return cp_cont_0(" .. args .. ");")
                    gem("#else")
                    gem("    TAIL return cp_cont_1(" .. args .. ");")
                    gem("#endif")
                    gem("}")
                    gem("")
                end
            end
        end
    end
end

-- Guarded host-FPU square root, with the same proof and continuation
-- contract as binary arithmetic.
for _, width in ipairs({ "s", "d" }) do
    local uint = width == "s" and "uint32_t" or "uint64_t"
    local host = width == "s" and "float" or "double"
    local iface = width == "s" and "i_float32" or "i_float64"
    local builtin = width == "s" and "__builtin_sqrtf" or "__builtin_sqrt"
    local boxed_mask = width == "s" and "UINT64_C(0xffffffff00000000)" or "UINT64_C(0)"
    for _, dynamic in ipairs({ false, true }) do
        local mode = dynamic and "dyn" or "rne"
        for d = 0, NSLOTS - 1 do
            gem(("extern \"C\" CONT void cp_fp_sqrt_%s_%s_%d(%s)"):format(width, mode, d, params))
            gem("{")
            gem("#ifdef HARD_FLOAT")
            gem("    const auto acc = std::bit_cast<cartesi::state_access>(sa);")
            gem("    const uint64_t fcsr = acc.read_fcsr();")
            gem("    if ((acc.read_mstatus() & cartesi::MSTATUS_FS_MASK) == cartesi::MSTATUS_FS_OFF) {")
            gem("        TAIL return cp_cont_1(" .. args .. ");")
            gem("    }")
            if dynamic then
                gem("    if (((fcsr >> cartesi::FCSR_FRM_SHIFT) & 7) != cartesi::FRM_RNE) {")
                gem("        TAIL return cp_cont_1(" .. args .. ");")
                gem("    }")
            end
            if width == "s" then
                gem(("    if ((r%d & %s) != %s) {"):format(d, boxed_mask, boxed_mask))
                gem("        TAIL return cp_cont_1(" .. args .. ");")
                gem("    }")
            end
            gem(("    const %s a = static_cast<%s>(r%d);"):format(uint, uint, d))
            gem("    if (acc.get_penumbra().hard_float_enabled == 0 ||")
            gem("        (cartesi::fcsr_fflags(fcsr) & cartesi::FFLAGS_NX_MASK) == 0 ||")
            gem(("        !cartesi::%s::is_zero_or_normal(a)) {"):format(iface))
            gem("        TAIL return cp_cont_1(" .. args .. ");")
            gem("    }")
            gem(("    const %s result = std::bit_cast<%s>(%s(std::bit_cast<%s>(a)));"):format(
                uint, uint, builtin, host))
            gem(("    if (!cartesi::%s::is_safe_result(result)) {"):format(iface))
            gem("        TAIL return cp_cont_1(" .. args .. ");")
            gem("    }")
            if width == "s" then
                gem(("    r%d = static_cast<uint64_t>(result) | %s;"):format(d, boxed_mask))
            else
                gem(("    r%d = result;"):format(d))
            end
            gem("    TAIL return cp_cont_0(" .. args .. ");")
            gem("#else")
            gem("    TAIL return cp_cont_1(" .. args .. ");")
            gem("#endif")
            gem("}")
            gem("")
        end
    end
end

-- Fused ternary arithmetic. AArch64 has architectural fused multiply-add.
-- On x86-64 the ordinary placement entries remain soft-only; alternate
-- target("fma") descriptors are emitted with a non-family suffix so startup
-- can substitute only those entries when the host supports FMA.
local FP_FMA_OPS = {
    fmadd = { false, false },
    fmsub = { false, true },
    fnmadd = { true, true },
    fnmsub = { true, false },
}
for _, width in ipairs({ "s", "d" }) do
    local uint = width == "s" and "uint32_t" or "uint64_t"
    local host = width == "s" and "float" or "double"
    local iface = width == "s" and "i_float32" or "i_float64"
    local builtin = width == "s" and "__builtin_fmaf" or "__builtin_fma"
    local sign = width == "s" and "cartesi::i_sfloat32::SIGN_MASK" or "cartesi::i_sfloat64::SIGN_MASK"
    local boxed_mask = width == "s" and "UINT64_C(0xffffffff00000000)" or "UINT64_C(0)"
    for _, dynamic in ipairs({ false, true }) do
        local mode = dynamic and "dyn" or "rne"
        for _, opname in ipairs(sem_sorted(FP_FMA_OPS)) do
            local negate_product, negate_addend = table.unpack(FP_FMA_OPS[opname])
            for d = 0, NSLOTS - 1 do
                for s2 = 0, NSLOTS - 1 do
                    local s3 = NSLOTS - 1
                    local function emit_fma(name, attribute, hard_condition)
                        gem(("extern \"C\" %sCONT void %s(%s)"):format(attribute, name, params))
                        gem("{")
                        gem("#if defined(HARD_FLOAT) && " .. hard_condition)
                        gem("    const auto acc = std::bit_cast<cartesi::state_access>(sa);")
                        gem("    const uint64_t fcsr = acc.read_fcsr();")
                        gem("    if ((acc.read_mstatus() & cartesi::MSTATUS_FS_MASK) == cartesi::MSTATUS_FS_OFF) {")
                        gem("        TAIL return cp_cont_1(" .. args .. ");")
                        gem("    }")
                        if dynamic then
                            gem("    if (((fcsr >> cartesi::FCSR_FRM_SHIFT) & 7) != cartesi::FRM_RNE) {")
                            gem("        TAIL return cp_cont_1(" .. args .. ");")
                            gem("    }")
                        end
                        if width == "s" then
                            gem(("    if ((r%d & %s) != %s || (r%d & %s) != %s || (r%d & %s) != %s) {"):format(
                                d, boxed_mask, boxed_mask, s2, boxed_mask, boxed_mask, s3, boxed_mask, boxed_mask))
                            gem("        TAIL return cp_cont_1(" .. args .. ");")
                            gem("    }")
                        end
                        gem(("    %s a = static_cast<%s>(r%d);"):format(uint, uint, d))
                        gem(("    const %s b = static_cast<%s>(r%d);"):format(uint, uint, s2))
                        gem(("    %s c = static_cast<%s>(r%d);"):format(uint, uint, s3))
                        if negate_product then
                            gem(("    a ^= %s;"):format(sign))
                        end
                        if negate_addend then
                            gem(("    c ^= %s;"):format(sign))
                        end
                        gem("    if (acc.get_penumbra().hard_float_enabled == 0 ||")
                        gem("        (cartesi::fcsr_fflags(fcsr) & cartesi::FFLAGS_NX_MASK) == 0 ||")
                        gem(
                            ("        !cartesi::%s::is_zero_or_normal(a) || " ..
                                "!cartesi::%s::is_zero_or_normal(b) ||"):format(iface, iface))
                        gem(("        !cartesi::%s::is_zero_or_normal(c)) {"):format(iface))
                        gem("        TAIL return cp_cont_1(" .. args .. ");")
                        gem("    }")
                        gem(("    const %s result = std::bit_cast<%s>(%s(std::bit_cast<%s>(a),"):format(
                            uint, uint, builtin, host))
                        gem(("        std::bit_cast<%s>(b), std::bit_cast<%s>(c)));"):format(host, host))
                        gem(("    if (!cartesi::%s::is_safe_result(result)) {"):format(iface))
                        gem("        TAIL return cp_cont_1(" .. args .. ");")
                        gem("    }")
                        if width == "s" then
                            gem(("    r%d = static_cast<uint64_t>(result) | %s;"):format(d, boxed_mask))
                        else
                            gem(("    r%d = result;"):format(d))
                        end
                        gem("    TAIL return cp_cont_0(" .. args .. ");")
                        gem("#else")
                        gem("    TAIL return cp_cont_1(" .. args .. ");")
                        gem("#endif")
                        gem("}")
                        gem("")
                    end
                    local base = ("cp_fp_%s_%s_%s_%d_%d"):format(opname, width, mode, d, s2)
                    emit_fma(base, "", "defined(__aarch64__)")
                    gem("#if defined(__x86_64__)")
                    emit_fma(base .. "_x86_fma", "__attribute__((target(\"fma\"))) ",
                        "defined(__x86_64__)")
                    gem("#endif")
                end
            end
        end
    end
end

-- Synthetic instruction words: rd=3, rs1=1, rs2=2 everywhere.
local function r_insn(opc, f3, f7)
    return (f7 << 25) | (2 << 20) | (1 << 15) | (f3 << 12) | (3 << 7) | opc
end
-- R-type and W/M groups: name -> { execute fn, insn }.
local SEM_REG_OPS = {
    add = { "execute_ADD<cartesi::rd_kind::xN>", r_insn(0x33, 0, 0) },
    sub = { "execute_SUB<cartesi::rd_kind::xN>", r_insn(0x33, 0, 0x20) },
    sll = { "execute_SLL<cartesi::rd_kind::xN>", r_insn(0x33, 1, 0) },
    slt = { "execute_SLT<cartesi::rd_kind::xN>", r_insn(0x33, 2, 0) },
    sltu = { "execute_SLTU<cartesi::rd_kind::xN>", r_insn(0x33, 3, 0) },
    ["xor"] = { "execute_XOR<cartesi::rd_kind::xN>", r_insn(0x33, 4, 0) },
    srl = { "execute_SRL<cartesi::rd_kind::xN>", r_insn(0x33, 5, 0) },
    sra = { "execute_SRA<cartesi::rd_kind::xN>", r_insn(0x33, 5, 0x20) },
    ["or"] = { "execute_OR<cartesi::rd_kind::xN>", r_insn(0x33, 6, 0) },
    ["and"] = { "execute_AND<cartesi::rd_kind::xN>", r_insn(0x33, 7, 0) },
    mul = { "execute_MUL<cartesi::rd_kind::xN>", r_insn(0x33, 0, 1) },
    mulh = { "execute_MULH<cartesi::rd_kind::xN>", r_insn(0x33, 1, 1) },
    mulhsu = { "execute_MULHSU<cartesi::rd_kind::xN>", r_insn(0x33, 2, 1) },
    mulhu = { "execute_MULHU<cartesi::rd_kind::xN>", r_insn(0x33, 3, 1) },
    ["div"] = { "execute_DIV<cartesi::rd_kind::xN>", r_insn(0x33, 4, 1) },
    divu = { "execute_DIVU<cartesi::rd_kind::xN>", r_insn(0x33, 5, 1) },
    rem = { "execute_REM<cartesi::rd_kind::xN>", r_insn(0x33, 6, 1) },
    remu = { "execute_REMU<cartesi::rd_kind::xN>", r_insn(0x33, 7, 1) },
    addw = { "execute_ADDW<cartesi::rd_kind::xN>", r_insn(0x3b, 0, 0) },
    subw = { "execute_SUBW<cartesi::rd_kind::xN>", r_insn(0x3b, 0, 0x20) },
    sllw = { "execute_SLLW<cartesi::rd_kind::xN>", r_insn(0x3b, 1, 0) },
    srlw = { "execute_SRLW<cartesi::rd_kind::xN>", r_insn(0x3b, 5, 0) },
    sraw = { "execute_SRAW<cartesi::rd_kind::xN>", r_insn(0x3b, 5, 0x20) },
    mulw = { "execute_MULW<cartesi::rd_kind::xN>", r_insn(0x3b, 0, 1) },
    divw = { "execute_DIVW<cartesi::rd_kind::xN>", r_insn(0x3b, 4, 1) },
    divuw = { "execute_DIVUW<cartesi::rd_kind::xN>", r_insn(0x3b, 5, 1) },
    remw = { "execute_REMW<cartesi::rd_kind::xN>", r_insn(0x3b, 6, 1) },
    remuw = { "execute_REMUW<cartesi::rd_kind::xN>", r_insn(0x3b, 7, 1) },
}
-- Branches: synthetic forward offset +8 (imm[4:1]=4 lands at insn bits 8-11).
local function b_insn(f3)
    return (2 << 20) | (1 << 15) | (f3 << 12) | (4 << 8) | 0x63
end
local SEM_BR_OPS = {
    beq = { "execute_BEQ", b_insn(0) },
    bne = { "execute_BNE", b_insn(1) },
    blt = { "execute_BLT", b_insn(4) },
    bge = { "execute_BGE", b_insn(5) },
    bltu = { "execute_BLTU", b_insn(6) },
    bgeu = { "execute_BGEU", b_insn(7) },
}

for _, name in ipairs(sem_sorted(SEM_REG_OPS)) do
    local fn_name, insn = SEM_REG_OPS[name][1], SEM_REG_OPS[name][2]
    for d = 0, NSLOTS - 1 do
        for s1 = 0, NSLOTS - 1 do
            for s2 = 0, NSLOTS - 1 do
                gem(("extern \"C\" CONT void cp_%s_%d_%d_%d(%s)"):format(name, d, s1, s2, params))
                gem("{")
                gem(("    uint64_t v1 = r%d;"):format(s1))
                gem(("    uint64_t v2 = r%d;"):format(s2))
                gem("    uint64_t vd = 0;")
                gem("    const cartesi::cp_slot_access acc(&v1, &v2, &vd);")
                gem("    uint64_t spc = 0;")
                gem(("    (void) cartesi::%s(acc, spc, 0x%08xu);"):format(fn_name, insn))
                gem(("    r%d = vd;"):format(d))
                gem("    TAIL return cp_cont_0(" .. args .. ");")
                gem("}")
                gem("")
            end
        end
    end
end

-- Greedy fusion, first terminal: C.SLLI rd,shamt; C.ADD rd,rs2. Both
-- instructions update the same guest register, so its source and destination
-- share one roster slot. Fixed shift families keep the fused stencil free of
-- a new semantic-immediate patch shape. This is selected only on AArch64,
-- where the compiler folds the pair to a shifted-register add.
gem("#if defined(__aarch64__)")
local function slli_insn(shamt)
    return (shamt << 20) | (1 << 15) | (1 << 12) | (3 << 7) | 0x13
end
for shamt = 1, 3 do
    for d = 0, NSLOTS - 1 do
        for s = 0, NSLOTS - 1 do
            gem(("extern \"C\" CONT void cp_slli_add_sh%d_%d_%d(%s)"):format(shamt, d, s, params))
            gem("{")
            gem(("    uint64_t shift_src = r%d;"):format(d))
            gem("    uint64_t unused = 0;")
            gem("    uint64_t shifted = 0;")
            gem("    const cartesi::cp_slot_access shift_acc(&shift_src, &unused, &shifted);")
            gem("    uint64_t spc = 0;")
            gem(("    (void) cartesi::execute_SLLI<cartesi::rd_kind::xN>(shift_acc, spc, 0x%08xu);"):
                format(slli_insn(shamt)))
            if d == s then
                gem("    uint64_t add_src = shifted;")
            else
                gem(("    uint64_t add_src = r%d;"):format(s))
            end
            gem("    uint64_t result = 0;")
            gem("    const cartesi::cp_slot_access add_acc(&shifted, &add_src, &result);")
            gem(("    (void) cartesi::execute_ADD<cartesi::rd_kind::xN>(add_acc, spc, 0x%08xu);"):
                format(SEM_REG_OPS.add[2]))
            gem(("    r%d = result;"):format(d))
            gem("    TAIL return cp_cont_0(" .. args .. ");")
            gem("}")
            gem("")
        end
    end
end

gem("#endif")
gem("")

-- The dominant sieve sequence has fixed shifts: SRLIW rd,rs1,5 followed by
-- C.SLLI rd,2. Unlike two independent immediate stencils, this semantic
-- stencil exposes both shifts directly to the host compiler and never
-- materializes either shift count in a roster slot.
local function srliw_insn(shamt)
    return (shamt << 20) | (1 << 15) | (5 << 12) | (3 << 7) | 0x1b
end
for d = 0, NSLOTS - 1 do
    for s = 0, NSLOTS - 1 do
        gem(("extern \"C\" CONT void cp_srliw5_slli2_%d_%d(%s)"):format(d, s, params))
        gem("{")
        gem(("    uint64_t shift_src = r%d;"):format(s))
        gem("    uint64_t unused = 0;")
        gem("    uint64_t first = 0;")
        gem("    const cartesi::cp_slot_access first_acc(&shift_src, &unused, &first);")
        gem("    uint64_t spc = 0;")
        gem(("    (void) cartesi::execute_SRLIW<cartesi::rd_kind::xN>(first_acc, spc, 0x%08xu);"):
            format(srliw_insn(5)))
        gem("    uint64_t result = 0;")
        gem("    const cartesi::cp_slot_access second_acc(&first, &unused, &result);")
        gem(("    (void) cartesi::execute_SLLI<cartesi::rd_kind::xN>(second_acc, spc, 0x%08xu);"):
            format(slli_insn(2)))
        gem(("    r%d = result;"):format(d))
        gem("    TAIL return cp_cont_0(" .. args .. ");")
        gem("}")
        gem("")
    end
end

-- These are the two same-destination SLLI;SRLI immediate shapes with useful
-- dynamic weight in the measured AArch64 workloads. Constant shifts let the
-- compiler select a single bitfield operation where profitable.
gem("#if defined(__aarch64__)")
local function srli_insn(shamt)
    return (shamt << 20) | (1 << 15) | (5 << 12) | (3 << 7) | 0x13
end
for _, shifts in ipairs({ { 10, 20 }, { 32, 32 } }) do
    local left, right = shifts[1], shifts[2]
    for d = 0, NSLOTS - 1 do
        for s = 0, NSLOTS - 1 do
            gem(("extern \"C\" CONT void cp_slli%d_srli%d_%d_%d(%s)"):format(left, right, d, s, params))
            gem("{")
            gem(("    uint64_t shift_src = r%d;"):format(s))
            gem("    uint64_t unused = 0;")
            gem("    uint64_t first = 0;")
            gem("    const cartesi::cp_slot_access first_acc(&shift_src, &unused, &first);")
            gem("    uint64_t spc = 0;")
            gem(("    (void) cartesi::execute_SLLI<cartesi::rd_kind::xN>(first_acc, spc, 0x%08xu);"):
                format(slli_insn(left)))
            gem("    uint64_t result = 0;")
            gem("    const cartesi::cp_slot_access second_acc(&first, &unused, &result);")
            gem(("    (void) cartesi::execute_SRLI<cartesi::rd_kind::xN>(second_acc, spc, 0x%08xu);"):
                format(srli_insn(right)))
            gem(("    r%d = result;"):format(d))
            gem("    TAIL return cp_cont_0(" .. args .. ");")
            gem("}")
            gem("")
        end
    end
end
gem("#endif")
gem("")

-- C.MV is a register copy, not an ADD with an x0 operand. Keeping it as a
-- two-slot family avoids allocating and retaining a roster slot for x0.
for d = 0, NSLOTS - 1 do
    for s = 0, NSLOTS - 1 do
        gem(('extern "C" CONT void cp_mv_%d_%d(%s)'):format(d, s, params))
        gem("{")
        if d ~= s then
            gem(("    r%d = r%d;"):format(d, s))
        end
        gem("    TAIL return cp_cont_0(" .. args .. ");")
        gem("}")
        gem("")
    end
end

-- Immediate stencils remain semantic stencils: the interpreter execute body
-- sees a fixed sentinel immediate, which the extractor validates and turns
-- into a patchable host-instruction field. No host operation is handwritten.
local IMM_SENTINEL = 0x5a5
local function i_insn(opc, f3)
    return (IMM_SENTINEL << 20) | (1 << 15) | (f3 << 12) | (3 << 7) | opc
end
local SEM_IMM_OPS = {
    addi = { "execute_ADDI<cartesi::rd_kind::xN>", i_insn(0x13, 0) },
    addiw = { "execute_ADDIW<cartesi::rd_kind::xN>", i_insn(0x1b, 0) },
}
for _, name in ipairs(sem_sorted(SEM_IMM_OPS)) do
    local fn_name, insn = SEM_IMM_OPS[name][1], SEM_IMM_OPS[name][2]
    for d = 0, NSLOTS - 1 do
        for s = 0, NSLOTS - 1 do
            gem(("extern \"C\" CONT void cp_%s_%d_%d(%s)"):format(name, d, s, params))
            gem("{")
            gem(("    uint64_t v1 = r%d;"):format(s))
            gem("    uint64_t v2 = 0;")
            gem("    uint64_t vd = 0;")
            gem("    const cartesi::cp_slot_access acc(&v1, &v2, &vd);")
            gem("    uint64_t spc = 0;")
            gem(("    (void) cartesi::%s(acc, spc, 0x%08xu);"):format(fn_name, insn))
            gem(("    r%d = vd;"):format(d))
            gem("    TAIL return cp_cont_0(" .. args .. ");")
            gem("}")
            gem("")
        end
    end
end

for _, name in ipairs(sem_sorted(SEM_BR_OPS)) do
    local fn_name, insn = SEM_BR_OPS[name][1], SEM_BR_OPS[name][2]
    for s1 = 0, NSLOTS - 1 do
        for s2 = 0, NSLOTS - 1 do
            gem(("extern \"C\" CONT void cp_%s_%d_%d(%s)"):format(name, s1, s2, params))
            gem("{")
            gem(("    uint64_t v1 = r%d;"):format(s1))
            gem(("    uint64_t v2 = r%d;"):format(s2))
            gem("    uint64_t vd = 0;")
            gem("    const cartesi::cp_slot_access acc(&v1, &v2, &vd);")
            gem("    uint64_t spc = 0x1000;")
            gem(("    (void) cartesi::%s(acc, spc, 0x%08xu);"):format(fn_name, insn))
            gem("    if (spc == 0x1000 + 8) {")
            gem("        TAIL return cp_cont_0(" .. args .. ");")
            gem("    }")
            gem("    TAIL return cp_cont_1(" .. args .. ");")
            gem("}")
            gem("")
        end
    end
end
-- Memory families: loads I-type imm=0 (formation pre-adds immediates),
-- stores S-type imm=0. Base slot binds rs1=1, store value binds rs2=2.
local function l_insn(f3)
    return (1 << 15) | (f3 << 12) | (3 << 7) | 0x03
end
local function s_insn(f3)
    return (2 << 20) | (1 << 15) | (f3 << 12) | 0x23
end
local SEM_LOAD_OPS = {
    lb = { "execute_LB<cartesi::rd_kind::xN>", l_insn(0) },
    lh = { "execute_LH<cartesi::rd_kind::xN>", l_insn(1) },
    lw = { "execute_LW<cartesi::rd_kind::xN>", l_insn(2) },
    ld = { "execute_LD<cartesi::rd_kind::xN>", l_insn(3) },
    lbu = { "execute_LBU<cartesi::rd_kind::xN>", l_insn(4) },
    lhu = { "execute_LHU<cartesi::rd_kind::xN>", l_insn(5) },
    lwu = { "execute_LWU<cartesi::rd_kind::xN>", l_insn(6) },
}
local SEM_STORE_OPS = {
    sb = { "execute_SB", s_insn(0) },
    sh = { "execute_SH", s_insn(1) },
    sw = { "execute_SW", s_insn(2) },
    sd = { "execute_SD", s_insn(3) },
}
-- x86-64 folds fixed contexts into address displacements, so compile all
-- four values for build-time differencing. AArch64 materializes one fixed-
-- width sentinel whose validated field is expanded into the same selector
-- data by the extractor.
local CTX_SLOT_BASES = arch == "x86_64" and { 0, 0x100, 0x200, 0x300 } or { 0x500 }
for _, name in ipairs(sem_sorted(SEM_LOAD_OPS)) do
    local fn_name, insn = SEM_LOAD_OPS[name][1], SEM_LOAD_OPS[name][2]
    for d = 0, NSLOTS - 1 do
        for src = 0, NSLOTS - 1 do
            for ctx, ctx_slot_base in ipairs(CTX_SLOT_BASES) do
                local suffix = #CTX_SLOT_BASES == 1 and "" or ("_ctx%d"):format(ctx - 1)
                gem(("extern \"C\" CONT void cp_%s_%d_%d%s(%s)"):format(name, d, src, suffix, params))
                gem("{")
                gem(("    uint64_t v1 = r%d;"):format(src))
                gem("    uint64_t v2 = 0;")
                gem("    uint64_t vd = 0;")
                gem(("    const cartesi::cp_mem_access acc(sa, &v1, &v2, &vd, 0x%x);"):format(ctx_slot_base))
                gem("    uint64_t spc = 0;")
                gem(("    const auto st = cartesi::%s(acc, spc, 0, 0x%08xu);"):format(fn_name, insn))
                gem("    if (st != cartesi::execute_status::success) {")
                gem("        TAIL return cp_cont_1(" .. args .. ");")
                gem("    }")
                gem(("    r%d = vd;"):format(d))
                gem("    TAIL return cp_cont_0(" .. args .. ");")
                gem("}")
                gem("")
            end
        end
    end
end
-- CSR families for the hot FP CSRs (fflags, frm, fcsr): the measured
-- fragment breakers in soft-float and libm code. The CSR index is baked
-- into the synthetic word, so read_csr/write_csr constant-fold to the one
-- CSR's accessors; the raise interception turns the FS-off trap into the
-- bail continuation before any architectural write. rd=x0 forms reuse the
-- full family with a scratch destination (the slot write is invisible);
-- csrrs/csrrc with rs1=x0 must not write the CSR at all, so they get a
-- dedicated read-only family with rs1=0 baked.
local function csr_insn(f3, csr, rs1)
    return (csr << 20) | (rs1 << 15) | (f3 << 12) | (3 << 7) | 0x73
end
local SEM_CSRS = { fflags = 0x001, frm = 0x002, fcsr = 0x003 }
local SEM_CSR_OPS = { csrrw = { "execute_CSRRW", 1 }, csrrs = { "execute_CSRRS", 2 }, csrrc = { "execute_CSRRC", 3 } }
for _, opname in ipairs(sem_sorted(SEM_CSR_OPS)) do
    local fn_name, f3 = SEM_CSR_OPS[opname][1], SEM_CSR_OPS[opname][2]
    for _, csrname in ipairs(sem_sorted(SEM_CSRS)) do
        local insn = csr_insn(f3, SEM_CSRS[csrname], 1)
        for d = 0, NSLOTS - 1 do
            for s1 = 0, NSLOTS - 1 do
                gem(("extern \"C\" CONT __attribute__((flatten)) void cp_%s_%s_%d_%d(%s)"):format(
                    opname, csrname, d, s1, params))
                gem("{")
                gem(("    uint64_t v1 = r%d;"):format(s1))
                gem("    uint64_t v2 = 0;")
                gem("    uint64_t vd = 0;")
                gem("    const cartesi::cp_mem_access acc(sa, &v1, &v2, &vd, UINT64_MAX);")
                gem("    uint64_t spc = 0;")
                gem(("    const auto st = cartesi::%s(acc, spc, 0, 0x%08xu);"):format(fn_name, insn))
                gem("    if (st != cartesi::execute_status::success) {")
                gem("        TAIL return cp_cont_1(" .. args .. ");")
                gem("    }")
                gem(("    r%d = vd;"):format(d))
                gem("    TAIL return cp_cont_0(" .. args .. ");")
                gem("}")
                gem("")
            end
        end
    end
end
for _, csrname in ipairs(sem_sorted(SEM_CSRS)) do
    local insn = csr_insn(2, SEM_CSRS[csrname], 0) -- csrrs rd, csr, x0: pure read
    for d = 0, NSLOTS - 1 do
        gem(("extern \"C\" CONT __attribute__((flatten)) void cp_csrr_%s_%d(%s)"):format(csrname, d, params))
        gem("{")
        gem("    uint64_t v1 = 0;")
        gem("    uint64_t v2 = 0;")
        gem("    uint64_t vd = 0;")
        gem("    const cartesi::cp_mem_access acc(sa, &v1, &v2, &vd, UINT64_MAX);")
        gem("    uint64_t spc = 0;")
        gem(("    const auto st = cartesi::execute_CSRRS(acc, spc, 0, 0x%08xu);"):format(insn))
        gem("    if (st != cartesi::execute_status::success) {")
        gem("        TAIL return cp_cont_1(" .. args .. ");")
        gem("    }")
        gem(("    r%d = vd;"):format(d))
        gem("    TAIL return cp_cont_0(" .. args .. ");")
        gem("}")
        gem("")
    end
end

for _, name in ipairs(sem_sorted(SEM_STORE_OPS)) do
    local fn_name, insn = SEM_STORE_OPS[name][1], SEM_STORE_OPS[name][2]
    for base = 0, NSLOTS - 1 do
        for val = 0, NSLOTS - 1 do
            for ctx, ctx_slot_base in ipairs(CTX_SLOT_BASES) do
                local suffix = #CTX_SLOT_BASES == 1 and "" or ("_ctx%d"):format(ctx - 1)
                gem(("extern \"C\" CONT void cp_%s_%d_%d%s(%s)"):format(name, base, val, suffix, params))
                gem("{")
                gem(("    uint64_t v1 = r%d;"):format(base))
                gem(("    uint64_t v2 = r%d;"):format(val))
                gem("    uint64_t vd = 0;")
                gem(("    const cartesi::cp_mem_access acc(sa, &v1, &v2, &vd, 0x%x);"):format(ctx_slot_base))
                gem("    uint64_t spc = 0;")
                gem(("    const auto st = cartesi::%s(acc, spc, 0, 0x%08xu);"):format(fn_name, insn))
                gem("    if (st != cartesi::execute_status::success) {")
                gem("        TAIL return cp_cont_1(" .. args .. ");")
                gem("    }")
                gem("    TAIL return cp_cont_0(" .. args .. ");")
                gem("}")
                gem("")
            end
        end
    end
end
-- Guest register file transfer: cp_gxl_<slot>_<reg> loads x[reg] into a
-- slot, cp_gxs_<slot>_<reg> stores a slot to x[reg], through the real
-- state access so the x-file offsets are the emulator's own. reg 0 is
-- excluded (x0 reads become li 0, writes are dropped at formation).
for slot = 0, NSLOTS - 1 do
    for reg = 1, 31 do
        gem(("extern \"C\" CONT void cp_gxl_%d_%d(%s)"):format(slot, reg, params))
        gem("{")
        gem("    const auto acc = std::bit_cast<cartesi::state_access>(sa);")
        gem(("    r%d = acc.read_x(%d);"):format(slot, reg))
        gem("    TAIL return cp_cont_0(" .. args .. ");")
        gem("}")
        gem("")
        gem(("extern \"C\" CONT void cp_gxs_%d_%d(%s)"):format(slot, reg, params))
        gem("{")
        gem("    const auto acc = std::bit_cast<cartesi::state_access>(sa);")
        gem(("    acc.write_x(%d, r%d);"):format(reg, slot))
        gem("    TAIL return cp_cont_0(" .. args .. ");")
        gem("}")
        gem("")
    end
end
gem("// NOLINTEND")
g:close()
