#!/usr/bin/env lua5.4
-- Emits the copy-and-patch stencil source (cp-stencils.c) for the backend of
-- copy-patch-rvvm.md.
--
-- The contract is purely positional over the preserve_none argument order
-- (AArch64: x20-x28 then x0-x7, x86-64: r12-r15, rdi, rsi, then more or
-- stack). Parameters are placed so the interpreter's pinned AArch64 roster
-- falls at its own registers: pc at position 4 (x23), countdown at 5 (x24),
-- fetch tag at 6 (x25), context at 8 (x27). Guest-value cache slots fill the
-- remaining positions and every stencil passes all parameters through, so
-- trace entry from a TC handler and exit into the fetch tail are plain
-- branches with no state movement.
--
-- Continuations are musttail calls to extern preserve_none symbols (direct
-- branch relocations, patchable, elidable on fallthrough). 64-bit values are
-- addresses of extern hole arrays: movz/movk chains under the AArch64 large
-- code model, movabs under the x86-64 small model with per-symbol large
-- model (clang) or medium model with sized arrays (GCC).
--
-- Usage: lua5.4 cp-gen-stencils.lua <structural.c> <semantic.cpp>
--
-- The structural TU is C, compiled bare-metal (value holes need ELF's
-- movz/movk relocations). The semantic TU is C++, compiled natively with
-- the host toolchain: it includes interpret.cpp so every instruction
-- stencil instantiates the interpreter's own execute body (single
-- semantic source), and its only relocations are continuation branches,
-- which every object format patches.

local out = assert(arg[1], "usage: cp-gen-stencils.lua <structural.c> <semantic.cpp>")
local sem_out = assert(arg[2], "usage: cp-gen-stencils.lua <structural.c> <semantic.cpp>")
local f = assert(io.open(out, "w"))

local NSLOTS = 7

local function emit(s) f:write(s, "\n") end

-- Parameter list: position 1 is the state access (the interpreter contract
-- keeps it in x20, and memory stencils consume it directly), positions 4,
-- 5, 6, 8 are the pinned roster, the rest are the seven guest cache slots.
local params_t = {}
local args_t = {}
local slot_param = {"sa", "r0", "r1", "pc", "cd", "fetch", "r2", "tcc", "r3", "r4", "r5", "r6"}
for _, name in ipairs(slot_param) do
    params_t[#params_t + 1] = "u64 " .. name
    args_t[#args_t + 1] = name
end
local params = table.concat(params_t, ", ")
local args = table.concat(args_t, ", ")

emit("/* Generated by tools/cp-gen-stencils.lua. Do not edit. */")
emit("")
emit("typedef unsigned long long u64;")
emit("typedef long long i64;")
emit("typedef unsigned int u32;")
emit("typedef int i32;")
emit("typedef __int128 i128;")
emit("typedef unsigned __int128 u128;")
emit("#define CONT __attribute__((preserve_none))")
emit("#define TAIL __attribute__((musttail))")
emit("")
emit("/* Continuation holes (patched to branch targets). */")
emit(("CONT extern void cp_cont_0(%s);"):format(params))
emit(("CONT extern void cp_cont_1(%s);"):format(params))
emit("/* 64-bit value holes. */")
emit("#if defined(__x86_64__) && defined(__clang__)")
emit("#define CP_HOLE __attribute__((model(\"large\")))")
emit("#else")
emit("#define CP_HOLE")
emit("#endif")
emit("/* Sized so GCC's medium model (-mlarge-data-threshold) makes them")
emit(" * large data, reached by movabs with R_X86_64_64. */")
emit("CP_HOLE extern char cp_imm64_0[65536];")
emit("CP_HOLE extern char cp_imm64_1[65536];")
emit("")

local function fn(name, body)
    emit(("CONT void %s(%s)"):format(name, params))
    emit("{")
    emit(body)
    emit("    TAIL return cp_cont_0(" .. args .. ");")
    emit("}")
    emit("")
end

-- Terminal stencil for the tests: store every parameter through a patched
-- pointer and return to the (ordinary, caller-saves-everything) host caller.
emit(("CONT void cp_store_exit(%s)"):format(params))
emit("{")
emit("    u64 *o = (u64 *)cp_imm64_0;")
for i, name in ipairs(slot_param) do
    emit(("    o[%d] = %s;"):format(i - 1, name))
end
emit("}")
emit("")

-- Trace entry tick guard: the trace body fits before the tick end only when
-- the countdown exceeds the trace's worst-case pending count (a patched
-- constant). Signed compare: the privileged path can drive the countdown
-- negative. Bail is continuation 1, the body is the elidable fallthrough.
emit(("CONT void cp_tick_guard(%s)"):format(params))
emit("{")
emit("    if ((i64)cd <= (i64)(u64)cp_imm64_0) {")
emit("        TAIL return cp_cont_1(" .. args .. ");")
emit("    }")
emit("    TAIL return cp_cont_0(" .. args .. ");")
emit("}")
emit("")

-- Side exit: move the fast pc by a signed delta from the trace head
-- (the typed fast pc is position-encoded, so exits add displacements,
-- never absolute values), charge the pending instruction count against
-- the countdown, and leave for the fetch-tail continuation.
emit(("CONT void cp_exit_stub(%s)"):format(params))
emit("{")
emit("    pc += (u64)cp_imm64_0;")
emit("    cd -= (u64)cp_imm64_1;")
emit("    TAIL return cp_cont_0(" .. args .. ");")
emit("}")
emit("")

-- li: slot d = constant.
for d = 0, NSLOTS - 1 do
    fn(("cp_li_%d"):format(d), ("    r%d = (u64)cp_imm64_0;"):format(d))
end

-- Far jump: tail call through a 64-bit hole, the per-heap island through
-- which exits reach the interpreter continuation beyond direct branch
-- range. No runtime assembler: the indirect branch is compiler-emitted.
emit(("typedef CONT void (*cp_cont_t)(%s);"):format(params))
emit(("CONT void cp_far_jump(%s)"):format(params))
emit("{")
emit("    /* Two-hole sum defeats the direct-branch fold: the compiler")
emit("     * cannot resolve sym+sym to one target, so it materializes and")
emit("     * branches through a register. Patched as target plus zero. */")
emit("    TAIL return ((cp_cont_t)((u64)cp_imm64_0 + (u64)cp_imm64_1))(" .. args .. ");")
emit("}")
emit("")

f:close()

-- Semantic TU: wrappers instantiating the interpreter's execute bodies.
local g = assert(io.open(sem_out, "w"))
local function gem(line) g:write(line, "\n") end

gem("/* Generated by tools/cp-gen-stencils.lua. Do not edit. */")
gem("// NOLINTBEGIN")
gem("#define TC_TRANSLATION_UNIT")
gem('#include "interpret.cpp"')
gem("")
gem("namespace cartesi {")
gem("struct cp_slot_access;")
gem("template <>")
gem("struct i_state_access_fast_addr<cp_slot_access> {")
gem("    using type = uint64_t;")
gem("};")
gem("// Binds the synthetic instruction's rs1=1, rs2=2, rd=3 to wrapper")
gem("// locals, so each execute body folds onto the placement's registers.")
gem("struct cp_slot_access : i_state_access<cp_slot_access>, i_accept_scoped_notes<cp_slot_access> {")
gem("    uint64_t *v1;")
gem("    uint64_t *v2;")
gem("    uint64_t *vd;")
gem("    cp_slot_access(uint64_t *a1, uint64_t *a2, uint64_t *ad) : v1(a1), v2(a2), vd(ad) {}")
gem("    static const char *do_get_name() {")
gem('        return "cp_slot_access";')
gem("    }")
gem("    uint64_t do_read_x(int i) const {")
gem("        return i == 1 ? *v1 : *v2;")
gem("    }")
gem("    void do_write_x(int /*i*/, uint64_t val) const {")
gem("        *vd = val;")
gem("    }")
gem("    // Exception-path surface instantiated by the branch bodies; dead")
gem("    // under the aligned synthetic offset and folded away, never run.")
gem("    static uint64_t do_read_iprv() { return 0; }")
gem("    static void do_write_iprv(uint64_t) {}")
gem("    static uint64_t do_read_medeleg() { return 0; }")
gem("    static uint64_t do_read_mideleg() { return 0; }")
gem("    static uint64_t do_read_mstatus() { return 0; }")
gem("    static void do_write_mstatus(uint64_t) {}")
gem("    static uint64_t do_read_mtvec() { return 0; }")
gem("    static uint64_t do_read_stvec() { return 0; }")
gem("    static uint64_t do_read_icycleinstret() { return 0; }")
gem("    static void do_write_icycleinstret(uint64_t) {}")
gem("    static void do_write_ilrsc(uint64_t) {}")
gem("    static void do_write_mcause(uint64_t) {}")
gem("    static void do_write_mepc(uint64_t) {}")
gem("    static void do_write_mtval(uint64_t) {}")
gem("    static void do_write_scause(uint64_t) {}")
gem("    static void do_write_sepc(uint64_t) {}")
gem("    static void do_write_stval(uint64_t) {}")
gem("    static uint64_t do_read_fetch_vf_offset() { return 0; }")
gem("};")
gem("")
gem("// Memory-op accessor: slots for the register file, everything else")
gem("// forwarded to the real state access reconstructed from the sa")
gem("// parameter, so the emitted probe is the committed hot TLB path")
gem("// against the emulator's own layout. The slow path is intercepted")
gem("// below and turned into a bail.")
gem("struct cp_mem_access;")
gem("template <>")
gem("struct i_state_access_fast_addr<cp_mem_access> {")
gem("    using type = uint64_t;")
gem("};")
gem("struct cp_mem_access : i_state_access<cp_mem_access>, i_accept_scoped_notes<cp_mem_access> {")
gem("    state_access s;")
gem("    uint64_t *v1;")
gem("    uint64_t *v2;")
gem("    uint64_t *vd;")
gem("    static_assert(sizeof(state_access) == sizeof(uint64_t));")
gem("    cp_mem_access(uint64_t sa_bits, uint64_t *a1, uint64_t *a2, uint64_t *ad)")
gem("        : s(std::bit_cast<state_access>(sa_bits)), v1(a1), v2(a2), vd(ad) {}")
gem("    static const char *do_get_name() {")
gem('        return "cp_mem_access";')
gem("    }")
gem("    uint64_t do_read_x(int i) const {")
gem("        return i == 1 ? *v1 : *v2;")
gem("    }")
gem("    void do_write_x(int /*i*/, uint64_t val) const {")
gem("        *vd = val;")
gem("    }")
gem("    uint64_t do_read_tlb_ctx_slot_base() const {")
gem("        return s.read_tlb_ctx_slot_base();")
gem("    }")
gem("    template <TLB_set_index E>")
gem("    uint64_t do_read_tlb_vaddr_page(uint64_t i) const {")
gem("        return static_cast<uint64_t>(s.template read_tlb_vaddr_page<E>(i));")
gem("    }")
gem("    // Lazy hot-slot init is an out-of-line cold member; in the")
gem("    // hit-or-bail shape an uninitialized slot stays a miss and the")
gem("    // interpreter initializes it portably after the bail.")
gem("    template <TLB_set_index E>")
gem("    uint64_t do_init_hot_tlb_slot(uint64_t i) const {")
gem("        return static_cast<uint64_t>(s.template read_tlb_vaddr_page<E>(i));")
gem("    }")
gem("    template <TLB_set_index E>")
gem("    bool do_verify_cold_tlb_slot(uint64_t i) const {")
gem("        return s.template verify_cold_tlb_slot<E>(i);")
gem("    }")
gem("    template <TLB_set_index E>")
gem("    uint64_t do_read_tlb_pma_index(uint64_t i) const {")
gem("        return s.template read_tlb_pma_index<E>(i);")
gem("    }")
gem("    template <TLB_set_index E>")
gem("    uint64_t do_read_tlb_vf_offset(uint64_t i) const {")
gem("        return static_cast<uint64_t>(s.template read_tlb_vf_offset<E>(i));")
gem("    }")
gem("    template <typename T, typename A>")
gem("    void do_read_memory_word(uint64_t faddr, uint64_t pma_index, T *pval) const {")
gem("        s.template read_memory_word<T, A>(host_addr{faddr}, pma_index, pval);")
gem("    }")
gem("    template <typename T, typename A>")
gem("    void do_write_memory_word(uint64_t faddr, uint64_t pma_index, T val) const {")
gem("        s.template write_memory_word<T, A>(host_addr{faddr}, pma_index, val);")
gem("    }")
gem("    // Exception-path surface, forwarded to the real accessor: correct")
gem("    // if reachable, dead under the intercepted slow path otherwise.")
for _, csr in ipairs({ "icycleinstret", "mstatus", "iprv", "mcause", "mepc", "mtval", "scause", "sepc",
    "stval" }) do
    gem(("    uint64_t do_read_%s() const {"):format(csr))
    gem(("        return s.read_%s();"):format(csr))
    gem("    }")
    gem(("    void do_write_%s(uint64_t val) const {"):format(csr))
    gem(("        s.write_%s(val);"):format(csr))
    gem("    }")
end
for _, csr in ipairs({ "medeleg", "mideleg", "mtvec", "stvec" }) do
    gem(("    uint64_t do_read_%s() const {"):format(csr))
    gem(("        return s.read_%s();"):format(csr))
    gem("    }")
end
gem("    void do_write_ilrsc(uint64_t val) const {")
gem("        s.write_ilrsc(val);")
gem("    }")
gem("};")
gem("")
gem("// Slow-path interception: found by argument-dependent lookup at the")
gem("// instantiation of read/write_virtual_memory for cp_mem_access and")
gem("// preferred by partial ordering. Mutates nothing and reports failure,")
gem("// so the wrapper bails and the interpreter re-executes the")
gem("// instruction portably, running the true slow path there.")
gem("template <typename T, typename STATE_ACCESS, bool RAISE_STORE_EXCEPTIONS = false>")
gem("    requires(std::is_same_v<STATE_ACCESS, cp_mem_access>)")
gem("static FORCE_INLINE std::pair<bool, uint64_t> read_virtual_memory_slow(const STATE_ACCESS /*a*/, uint64_t pc,")
gem("    uint64_t /*mcycle*/, uint64_t /*vaddr*/, T * /*pval*/) {")
gem("    return {false, pc};")
gem("}")
gem("template <typename T, typename STATE_ACCESS>")
gem("    requires(std::is_same_v<STATE_ACCESS, cp_mem_access>)")
gem("static FORCE_INLINE std::pair<execute_status, uint64_t> write_virtual_memory_slow(const STATE_ACCESS /*a*/,")
gem("    uint64_t pc, uint64_t /*mcycle*/, uint64_t /*vaddr*/, uint64_t /*val64*/) {")
gem("    return {execute_status::failure, pc};")
gem("}")
gem("} // namespace cartesi")
gem("")
gem("typedef unsigned long long u64;")
gem("#define CONT __attribute__((preserve_none))")
gem("#define TAIL __attribute__((musttail))")
gem(("extern \"C\" CONT void cp_cont_0(%s);"):format(params))
gem(("extern \"C\" CONT void cp_cont_1(%s);"):format(params))
gem("")

-- Synthetic instruction words: rd=3, rs1=1, rs2=2 everywhere.
local function r_insn(opc, f3, f7)
    return (f7 << 25) | (2 << 20) | (1 << 15) | (f3 << 12) | (3 << 7) | opc
end
-- R-type and W/M groups: name -> { execute fn, insn }.
local SEM_REG_OPS = {
    add = { "execute_ADD<cartesi::rd_kind::xN>", r_insn(0x33, 0, 0) },
    sub = { "execute_SUB<cartesi::rd_kind::xN>", r_insn(0x33, 0, 0x20) },
    sll = { "execute_SLL<cartesi::rd_kind::xN>", r_insn(0x33, 1, 0) },
    slt = { "execute_SLT<cartesi::rd_kind::xN>", r_insn(0x33, 2, 0) },
    sltu = { "execute_SLTU<cartesi::rd_kind::xN>", r_insn(0x33, 3, 0) },
    ["xor"] = { "execute_XOR<cartesi::rd_kind::xN>", r_insn(0x33, 4, 0) },
    srl = { "execute_SRL<cartesi::rd_kind::xN>", r_insn(0x33, 5, 0) },
    sra = { "execute_SRA<cartesi::rd_kind::xN>", r_insn(0x33, 5, 0x20) },
    ["or"] = { "execute_OR<cartesi::rd_kind::xN>", r_insn(0x33, 6, 0) },
    ["and"] = { "execute_AND<cartesi::rd_kind::xN>", r_insn(0x33, 7, 0) },
    mul = { "execute_MUL<cartesi::rd_kind::xN>", r_insn(0x33, 0, 1) },
    mulh = { "execute_MULH<cartesi::rd_kind::xN>", r_insn(0x33, 1, 1) },
    mulhsu = { "execute_MULHSU<cartesi::rd_kind::xN>", r_insn(0x33, 2, 1) },
    mulhu = { "execute_MULHU<cartesi::rd_kind::xN>", r_insn(0x33, 3, 1) },
    ["div"] = { "execute_DIV<cartesi::rd_kind::xN>", r_insn(0x33, 4, 1) },
    divu = { "execute_DIVU<cartesi::rd_kind::xN>", r_insn(0x33, 5, 1) },
    rem = { "execute_REM<cartesi::rd_kind::xN>", r_insn(0x33, 6, 1) },
    remu = { "execute_REMU<cartesi::rd_kind::xN>", r_insn(0x33, 7, 1) },
    addw = { "execute_ADDW<cartesi::rd_kind::xN>", r_insn(0x3b, 0, 0) },
    subw = { "execute_SUBW<cartesi::rd_kind::xN>", r_insn(0x3b, 0, 0x20) },
    sllw = { "execute_SLLW<cartesi::rd_kind::xN>", r_insn(0x3b, 1, 0) },
    srlw = { "execute_SRLW<cartesi::rd_kind::xN>", r_insn(0x3b, 5, 0) },
    sraw = { "execute_SRAW<cartesi::rd_kind::xN>", r_insn(0x3b, 5, 0x20) },
    mulw = { "execute_MULW<cartesi::rd_kind::xN>", r_insn(0x3b, 0, 1) },
    divw = { "execute_DIVW<cartesi::rd_kind::xN>", r_insn(0x3b, 4, 1) },
    divuw = { "execute_DIVUW<cartesi::rd_kind::xN>", r_insn(0x3b, 5, 1) },
    remw = { "execute_REMW<cartesi::rd_kind::xN>", r_insn(0x3b, 6, 1) },
    remuw = { "execute_REMUW<cartesi::rd_kind::xN>", r_insn(0x3b, 7, 1) },
}
-- Branches: synthetic forward offset +8 (imm[4:1]=4 lands at insn bits 8-11).
local function b_insn(f3)
    return (2 << 20) | (1 << 15) | (f3 << 12) | (4 << 8) | 0x63
end
local SEM_BR_OPS = {
    beq = { "execute_BEQ", b_insn(0) },
    bne = { "execute_BNE", b_insn(1) },
    blt = { "execute_BLT", b_insn(4) },
    bge = { "execute_BGE", b_insn(5) },
    bltu = { "execute_BLTU", b_insn(6) },
    bgeu = { "execute_BGEU", b_insn(7) },
}

local function sem_sorted(t)
    local names = {}
    for name in pairs(t) do
        names[#names + 1] = name
    end
    table.sort(names)
    return names
end

for _, name in ipairs(sem_sorted(SEM_REG_OPS)) do
    local fn_name, insn = SEM_REG_OPS[name][1], SEM_REG_OPS[name][2]
    for d = 0, NSLOTS - 1 do
        for s1 = 0, NSLOTS - 1 do
            for s2 = 0, NSLOTS - 1 do
                gem(("extern \"C\" CONT void cp_%s_%d_%d_%d(%s)"):format(name, d, s1, s2, params))
                gem("{")
                gem(("    uint64_t v1 = r%d;"):format(s1))
                gem(("    uint64_t v2 = r%d;"):format(s2))
                gem("    uint64_t vd = 0;")
                gem("    const cartesi::cp_slot_access acc(&v1, &v2, &vd);")
                gem("    uint64_t spc = 0;")
                gem(("    (void) cartesi::%s(acc, spc, 0x%08xu);"):format(fn_name, insn))
                gem(("    r%d = vd;"):format(d))
                gem("    TAIL return cp_cont_0(" .. args .. ");")
                gem("}")
                gem("")
            end
        end
    end
end

for _, name in ipairs(sem_sorted(SEM_BR_OPS)) do
    local fn_name, insn = SEM_BR_OPS[name][1], SEM_BR_OPS[name][2]
    for s1 = 0, NSLOTS - 1 do
        for s2 = 0, NSLOTS - 1 do
            gem(("extern \"C\" CONT void cp_%s_%d_%d(%s)"):format(name, s1, s2, params))
            gem("{")
            gem(("    uint64_t v1 = r%d;"):format(s1))
            gem(("    uint64_t v2 = r%d;"):format(s2))
            gem("    uint64_t vd = 0;")
            gem("    const cartesi::cp_slot_access acc(&v1, &v2, &vd);")
            gem("    uint64_t spc = 0x1000;")
            gem(("    (void) cartesi::%s(acc, spc, 0x%08xu);"):format(fn_name, insn))
            gem("    if (spc == 0x1000 + 8) {")
            gem("        TAIL return cp_cont_0(" .. args .. ");")
            gem("    }")
            gem("    TAIL return cp_cont_1(" .. args .. ");")
            gem("}")
            gem("")
        end
    end
end
-- Memory families: loads I-type imm=0 (formation pre-adds immediates),
-- stores S-type imm=0. Base slot binds rs1=1, store value binds rs2=2.
local function l_insn(f3)
    return (1 << 15) | (f3 << 12) | (3 << 7) | 0x03
end
local function s_insn(f3)
    return (2 << 20) | (1 << 15) | (f3 << 12) | 0x23
end
local SEM_LOAD_OPS = {
    lb = { "execute_LB<cartesi::rd_kind::xN>", l_insn(0) },
    lh = { "execute_LH<cartesi::rd_kind::xN>", l_insn(1) },
    lw = { "execute_LW<cartesi::rd_kind::xN>", l_insn(2) },
    ld = { "execute_LD<cartesi::rd_kind::xN>", l_insn(3) },
    lbu = { "execute_LBU<cartesi::rd_kind::xN>", l_insn(4) },
    lhu = { "execute_LHU<cartesi::rd_kind::xN>", l_insn(5) },
    lwu = { "execute_LWU<cartesi::rd_kind::xN>", l_insn(6) },
}
local SEM_STORE_OPS = {
    sb = { "execute_SB", s_insn(0) },
    sh = { "execute_SH", s_insn(1) },
    sw = { "execute_SW", s_insn(2) },
    sd = { "execute_SD", s_insn(3) },
}
for _, name in ipairs(sem_sorted(SEM_LOAD_OPS)) do
    local fn_name, insn = SEM_LOAD_OPS[name][1], SEM_LOAD_OPS[name][2]
    for d = 0, NSLOTS - 1 do
        for src = 0, NSLOTS - 1 do
            gem(("extern \"C\" CONT void cp_%s_%d_%d(%s)"):format(name, d, src, params))
            gem("{")
            gem(("    uint64_t v1 = r%d;"):format(src))
            gem("    uint64_t v2 = 0;")
            gem("    uint64_t vd = 0;")
            gem("    const cartesi::cp_mem_access acc(sa, &v1, &v2, &vd);")
            gem("    uint64_t spc = 0;")
            gem(("    const auto st = cartesi::%s(acc, spc, 0, 0x%08xu);"):format(fn_name, insn))
            gem("    if (st != cartesi::execute_status::success) {")
            gem("        TAIL return cp_cont_1(" .. args .. ");")
            gem("    }")
            gem(("    r%d = vd;"):format(d))
            gem("    TAIL return cp_cont_0(" .. args .. ");")
            gem("}")
            gem("")
        end
    end
end
for _, name in ipairs(sem_sorted(SEM_STORE_OPS)) do
    local fn_name, insn = SEM_STORE_OPS[name][1], SEM_STORE_OPS[name][2]
    for base = 0, NSLOTS - 1 do
        for val = 0, NSLOTS - 1 do
            gem(("extern \"C\" CONT void cp_%s_%d_%d(%s)"):format(name, base, val, params))
            gem("{")
            gem(("    uint64_t v1 = r%d;"):format(base))
            gem(("    uint64_t v2 = r%d;"):format(val))
            gem("    uint64_t vd = 0;")
            gem("    const cartesi::cp_mem_access acc(sa, &v1, &v2, &vd);")
            gem("    uint64_t spc = 0;")
            gem(("    const auto st = cartesi::%s(acc, spc, 0, 0x%08xu);"):format(fn_name, insn))
            gem("    if (st != cartesi::execute_status::success) {")
            gem("        TAIL return cp_cont_1(" .. args .. ");")
            gem("    }")
            gem("    TAIL return cp_cont_0(" .. args .. ");")
            gem("}")
            gem("")
        end
    end
end
-- Guest register file transfer: cp_gxl_<slot>_<reg> loads x[reg] into a
-- slot, cp_gxs_<slot>_<reg> stores a slot to x[reg], through the real
-- state access so the x-file offsets are the emulator's own. reg 0 is
-- excluded (x0 reads become li 0, writes are dropped at formation).
for slot = 0, NSLOTS - 1 do
    for reg = 1, 31 do
        gem(("extern \"C\" CONT void cp_gxl_%d_%d(%s)"):format(slot, reg, params))
        gem("{")
        gem("    const auto acc = std::bit_cast<cartesi::state_access>(sa);")
        gem(("    r%d = acc.read_x(%d);"):format(slot, reg))
        gem("    TAIL return cp_cont_0(" .. args .. ");")
        gem("}")
        gem("")
        gem(("extern \"C\" CONT void cp_gxs_%d_%d(%s)"):format(slot, reg, params))
        gem("{")
        gem("    const auto acc = std::bit_cast<cartesi::state_access>(sa);")
        gem(("    acc.write_x(%d, r%d);"):format(reg, slot))
        gem("    TAIL return cp_cont_0(" .. args .. ");")
        gem("}")
        gem("")
    end
end
gem("// NOLINTEND")
g:close()
