#!/usr/bin/env lua5.4
-- Emits the copy-and-patch stencil source (cp-stencils.c) for the backend of
-- copy-patch-rvvm.md.
--
-- The contract is purely positional over the preserve_none argument order
-- (AArch64: x20-x28 then x0-x7, x86-64: r12-r15, rdi, rsi, then more or
-- stack). Parameters are placed so the interpreter's pinned AArch64 roster
-- falls at its own registers: pc at position 4 (x23), countdown at 5 (x24),
-- fetch tag at 6 (x25), context at 8 (x27). Guest-value cache slots fill the
-- remaining positions and every stencil passes all parameters through, so
-- trace entry from a TC handler and exit into the fetch tail are plain
-- branches with no state movement.
--
-- Continuations are musttail calls to extern preserve_none symbols (direct
-- branch relocations, patchable, elidable on fallthrough). 64-bit values are
-- addresses of extern hole arrays: movz/movk chains under the AArch64 large
-- code model, movabs under the x86-64 small model with per-symbol large
-- model (clang) or medium model with sized arrays (GCC).
--
-- Usage: lua5.4 cp-gen-stencils.lua <output.c>

local out = assert(arg[1], "usage: cp-gen-stencils.lua <output.c>")
local f = assert(io.open(out, "w"))

local NSLOTS = 8

local function emit(s) f:write(s, "\n") end

-- Parameter list: positions 4, 5, 6, 8 are the pinned roster.
local params_t = {}
local args_t = {}
local slot_param = {"r0", "r1", "r2", "pc", "cd", "fetch", "r3", "tcc", "r4", "r5", "r6", "r7"}
for _, name in ipairs(slot_param) do
    params_t[#params_t + 1] = "u64 " .. name
    args_t[#args_t + 1] = name
end
local params = table.concat(params_t, ", ")
local args = table.concat(args_t, ", ")

emit("/* Generated by tools/cp-gen-stencils.lua. Do not edit. */")
emit("")
emit("typedef unsigned long long u64;")
emit("typedef long long i64;")
emit("typedef unsigned int u32;")
emit("typedef int i32;")
emit("typedef __int128 i128;")
emit("typedef unsigned __int128 u128;")
emit("#define CONT __attribute__((preserve_none))")
emit("#define TAIL __attribute__((musttail))")
emit("")
emit("/* Continuation holes (patched to branch targets). */")
emit(("CONT extern void cp_cont_0(%s);"):format(params))
emit(("CONT extern void cp_cont_1(%s);"):format(params))
emit("/* 64-bit value holes. */")
emit("#if defined(__x86_64__) && defined(__clang__)")
emit("#define CP_HOLE __attribute__((model(\"large\")))")
emit("#else")
emit("#define CP_HOLE")
emit("#endif")
emit("/* Sized so GCC's medium model (-mlarge-data-threshold) makes them")
emit(" * large data, reached by movabs with R_X86_64_64. */")
emit("CP_HOLE extern char cp_imm64_0[65536];")
emit("CP_HOLE extern char cp_imm64_1[65536];")
emit("")

local function fn(name, body)
    emit(("CONT void %s(%s)"):format(name, params))
    emit("{")
    emit(body)
    emit("    TAIL return cp_cont_0(" .. args .. ");")
    emit("}")
    emit("")
end

-- Terminal stencil for the tests: store every parameter through a patched
-- pointer and return to the (ordinary, caller-saves-everything) host caller.
emit(("CONT void cp_store_exit(%s)"):format(params))
emit("{")
emit("    u64 *o = (u64 *)cp_imm64_0;")
for i, name in ipairs(slot_param) do
    emit(("    o[%d] = %s;"):format(i - 1, name))
end
emit("}")
emit("")

-- Trace entry tick guard: the trace body fits before the tick end only when
-- the countdown exceeds the trace's worst-case pending count (a patched
-- constant). Signed compare: the privileged path can drive the countdown
-- negative. Bail is continuation 1, the body is the elidable fallthrough.
emit(("CONT void cp_tick_guard(%s)"):format(params))
emit("{")
emit("    if ((i64)cd <= (i64)(u64)cp_imm64_0) {")
emit("        TAIL return cp_cont_1(" .. args .. ");")
emit("    }")
emit("    TAIL return cp_cont_0(" .. args .. ");")
emit("}")
emit("")

-- Side exit: materialize the architectural pc (patched constant), charge the
-- pending instruction count against the countdown (patched constant), and
-- leave for the fetch-tail continuation.
emit(("CONT void cp_exit_stub(%s)"):format(params))
emit("{")
emit("    pc = (u64)cp_imm64_0;")
emit("    cd -= (u64)cp_imm64_1;")
emit("    TAIL return cp_cont_0(" .. args .. ");")
emit("}")
emit("")

-- li: slot d = constant.
for d = 0, NSLOTS - 1 do
    fn(("cp_li_%d"):format(d), ("    r%d = (u64)cp_imm64_0;"):format(d))
end

-- RV64IM register-register ops, exact RISC-V semantics over u64 slots.
-- %a and %b substitute the source slots, the result is assigned to the
-- destination slot. Division and remainder carry the RISC-V zero and
-- overflow rules inside the stencil (branchy but call-free).
local REG_OPS = {
    add = "%a + %b",
    sub = "%a - %b",
    ["and"] = "%a & %b",
    ["or"] = "%a | %b",
    ["xor"] = "%a ^ %b",
    sll = "%a << (%b & 63)",
    srl = "%a >> (%b & 63)",
    sra = "(u64)((i64)%a >> (%b & 63))",
    slt = "((i64)%a < (i64)%b) ? 1 : 0",
    sltu = "(%a < %b) ? 1 : 0",
    addw = "(u64)(i64)(i32)((u32)%a + (u32)%b)",
    subw = "(u64)(i64)(i32)((u32)%a - (u32)%b)",
    sllw = "(u64)(i64)(i32)((u32)%a << (%b & 31))",
    srlw = "(u64)(i64)(i32)((u32)%a >> (%b & 31))",
    sraw = "(u64)(i64)((i32)%a >> (%b & 31))",
    mul = "%a * %b",
    mulw = "(u64)(i64)(i32)((u32)%a * (u32)%b)",
    mulh = "(u64)(i64)(((i128)(i64)%a * (i128)(i64)%b) >> 64)",
    mulhu = "(u64)(((u128)%a * (u128)%b) >> 64)",
    mulhsu = "(u64)(i64)(((i128)(i64)%a * (i128)%b) >> 64)",
    ["div"] = "(%b == 0) ? (u64)-1 : ((%a == 0x8000000000000000ULL && %b == (u64)-1) ? %a : (u64)((i64)%a / (i64)%b))",
    divu = "(%b == 0) ? (u64)-1 : (%a / %b)",
    ["rem"] = "(%b == 0) ? %a : ((%a == 0x8000000000000000ULL && %b == (u64)-1) ? 0 : (u64)((i64)%a % (i64)%b))",
    remu = "(%b == 0) ? %a : (%a % %b)",
    divw = "((u32)%b == 0) ? (u64)-1 : (((u32)%a == 0x80000000U && (i32)%b == -1) ? (u64)(i64)(i32)%a : (u64)(i64)((i32)%a / (i32)%b))",
    divuw = "((u32)%b == 0) ? (u64)-1 : (u64)(i64)(i32)((u32)%a / (u32)%b)",
    remw = "((u32)%b == 0) ? (u64)(i64)(i32)%a : (((u32)%a == 0x80000000U && (i32)%b == -1) ? 0 : (u64)(i64)((i32)%a % (i32)%b))",
    remuw = "((u32)%b == 0) ? (u64)(i64)(i32)%a : (u64)(i64)(i32)((u32)%a % (u32)%b)",
}
local reg_names = {}
for name in pairs(REG_OPS) do
    reg_names[#reg_names + 1] = name
end
table.sort(reg_names)
for _, name in ipairs(reg_names) do
    local expr = REG_OPS[name]
    for d = 0, NSLOTS - 1 do
        for s1 = 0, NSLOTS - 1 do
            for s2 = 0, NSLOTS - 1 do
                local e = expr:gsub("%%a", "r" .. s1):gsub("%%b", "r" .. s2)
                fn(("cp_%s_%d_%d_%d"):format(name, d, s1, s2), ("    r%d = %s;"):format(d, e))
            end
        end
    end
end

-- Immediate forms: the constant is a 64-bit hole materialized by the
-- stencil; encodable-immediate shapes are a later measured optimization.
local IMM_OPS = {
    addi = "%a + imm",
    andi = "%a & imm",
    ori = "%a | imm",
    xori = "%a ^ imm",
    slti = "((i64)%a < (i64)imm) ? 1 : 0",
    sltiu = "(%a < imm) ? 1 : 0",
    slli = "%a << (imm & 63)",
    srli = "%a >> (imm & 63)",
    srai = "(u64)((i64)%a >> (imm & 63))",
    addiw = "(u64)(i64)(i32)((u32)%a + (u32)imm)",
    slliw = "(u64)(i64)(i32)((u32)%a << (imm & 31))",
    srliw = "(u64)(i64)(i32)((u32)%a >> (imm & 31))",
    sraiw = "(u64)(i64)((i32)%a >> (imm & 31))",
}
local imm_names = {}
for name in pairs(IMM_OPS) do
    imm_names[#imm_names + 1] = name
end
table.sort(imm_names)
for _, name in ipairs(imm_names) do
    local expr = IMM_OPS[name]
    for d = 0, NSLOTS - 1 do
        for s = 0, NSLOTS - 1 do
            local e = expr:gsub("%%a", "r" .. s)
            fn(("cp_%s_%d_%d"):format(name, d, s),
                ("    u64 imm = (u64)cp_imm64_0;\n    r%d = %s;"):format(d, e))
        end
    end
end

-- Branch guards, all six conditions: taken continuation 0 (the recorded
-- direction), fallthrough continuation 1.
local BR_OPS = {
    beq = "%a == %b",
    bne = "%a != %b",
    blt = "(i64)%a < (i64)%b",
    bge = "(i64)%a >= (i64)%b",
    bltu = "%a < %b",
    bgeu = "%a >= %b",
}
local br_names = {}
for name in pairs(BR_OPS) do
    br_names[#br_names + 1] = name
end
table.sort(br_names)
for _, name in ipairs(br_names) do
    local cond = BR_OPS[name]
    for s1 = 0, NSLOTS - 1 do
        for s2 = 0, NSLOTS - 1 do
            local c = cond:gsub("%%a", "r" .. s1):gsub("%%b", "r" .. s2)
            emit(("CONT void cp_%s_%d_%d(%s)"):format(name, s1, s2, params))
            emit("{")
            emit(("    if (%s) {"):format(c))
            emit("        TAIL return cp_cont_0(" .. args .. ");")
            emit("    }")
            emit("    TAIL return cp_cont_1(" .. args .. ");")
            emit("}")
            emit("")
        end
    end
end

-- ld: slot d = *(u64 *)(slot s + constant). Memory-shape probe; the real
-- hot TLB family replaces this in the backend integration.
for d = 0, NSLOTS - 1 do
    for s = 0, NSLOTS - 1 do
        fn(("cp_ld_%d_%d"):format(d, s), ("    r%d = *(const u64 *)(r%d + (u64)cp_imm64_0);"):format(d, s))
    end
end

f:close()
