// Copyright Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: LGPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU Lesser General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
// A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
// details.
//
// You should have received a copy of the GNU Lesser General Public License along
// with this program (see COPYING). If not, see <https://www.gnu.org/licenses/>.
//

/// \file
/// \brief The tail-call interpreter's shape selection and handler ABI.
/// \details Everything that fixes the handler contract lives here so that the
/// interpreter translation unit and the copy-and-patch stencil translation
/// unit (interpret-tc-stencils.cpp) compile against one definition of it: the
/// feature flags, the loop context layout, the pinned register set, the
/// handler parameter macros, and the countdown. A stencil is only relocatable
/// into a trace because its code was compiled against exactly the contract the
/// interpreter it will be spliced into was compiled against, so this header
/// must be included with identical -DTC_* flags in both units; the generated
/// stencil table carries an ABI fingerprint that the interpreter static_asserts.
///
/// Included by a translation unit that has already included interpret.cpp,
/// from inside namespace cartesi.

// NOLINTBEGIN(cppcoreguidelines-macro-usage)
// Measurement shell for the tracing plan (tail-call.md section 8b, step 1):
// LuaJIT-shaped selective hotcounts and a trace-head probe at taken backward
// branches and call targets, with no recording and no traces. -DTC_JIT_SHELL=1
// compiles the hooks in; the difference against the same build without them is
// the profiling shell's cost.
//
// AOT trace execution (section 8b, step 2): -DTC_AOT=1 additionally fills the
// head table from offline-captured traces generated by gen-tc-traces.lua
// (path in TC_AOT_TRACES) and dispatches into them from the hook sites. The
// trace bodies replay recorded instruction sequences through the same
// execute_* semantics with per-step guards; this is an execution oracle in
// tracing.md's sense: recorded code bytes are not re-verified against guest
// memory, so it is valid for gated benchmarks, not production.
#ifndef TC_AOT
#define TC_AOT 0
#endif

// Online trace recording (section 8b, step 3): -DTC_ONLINE=1 records trace
// bodies at hotcount trips into fixed statically-allocated pools (LuaJIT's
// memory policy: nothing is allocated at runtime, so nothing can fail at
// runtime), installs them by bump pointer, flushes everything when the pool
// fills, and blacklists heads whose recordings keep failing. Installed heads
// register in the shell's head table so the probe counts would-be entries;
// execution of online recordings waits for the backend step.
#ifndef TC_ONLINE
#define TC_ONLINE 0
#endif

// Page-segment fetch validation (tail-call.md section 8c): the chain
// countdown is additionally bounded by the number of fall-through fetches
// that provably stay within the validated page, so in-segment dispatches
// need no per-instruction fetch-cache check; only control transfers and
// cold paths validate pages, tightening the bound when pc moves, and
// segment expiry re-derives the bound in-chain without leaving to the
// outer loop. Off by default until measured (-DTC_PAGE_SEGMENT=1).
#ifndef TC_PAGE_SEGMENT
#define TC_PAGE_SEGMENT 0
#endif

// Coverage accounting: counts the guest instructions that retire inside
// compiled code, which is the number that says whether the backend or its
// surroundings are the limit. It costs a store at every trace entry and a
// subtract at every exit, so it is off unless asked for (-DTC_JIT_COVERAGE=1).
#ifndef TC_JIT_COVERAGE
#define TC_JIT_COVERAGE 0
#endif

// Copy-and-patch backend (tail-call.md section 5.20): -DTC_JIT=1 compiles the
// stencil table and the code cache in, and the recorder of TC_ONLINE installs
// compiled traces instead of discarding them. This is section 8b step 4, the
// backend the AOT oracle of step 2 measured the ceiling for.
#ifndef TC_JIT
#define TC_JIT 0
#endif

#if TC_JIT && !TC_ONLINE
#error "TC_JIT needs the online recorder to have something to compile; build with TC_ONLINE=1"
#endif

#if TC_PAGE_SEGMENT && (TC_AOT || TC_ONLINE)
#error "TC_PAGE_SEGMENT is not yet composed with the trace prototypes"
#endif

#ifndef TC_JIT_SHELL
#if TC_AOT || TC_ONLINE
#define TC_JIT_SHELL 1 // trace dispatch and recording ride the shell's hook sites
#else
#define TC_JIT_SHELL 0
#endif
#endif

// Hotness gate: loops trip at half this many events, calls at all of them.
// The pure shell keeps LuaJIT's low bar (its cost was measured with it); the
// online recorder observes execution one instruction at a time, so its
// sessions are expensive and the gate follows the PyPy/capture-build order
// of magnitude instead, starving the lukewarm-head tail.
#ifndef TC_HOT_RESET
#if TC_ONLINE
#define TC_HOT_RESET 2048
#else
#define TC_HOT_RESET 112
#endif
#endif

// How many trace heads the direct-mapped table can hold. LuaJIT's shape sized
// the shell's table for measuring the probe's cost, not for holding a working
// set; a compiled trace is only reachable while its head still owns a slot, so
// this bounds coverage directly. The table lives in the penumbra scratch area
// with the rest of the loop context, which is what caps it.
#ifndef TC_HEAD_SLOTS
#define TC_HEAD_SLOTS 64
#endif

#if TC_JIT_SHELL
/// \brief Selective profiling state: 64 colliding 16-bit hotcounts (loops
/// weighted double, hot after 56 loop events or 112 call events) and a
/// direct-mapped trace-head table, empty in the shell so probes always miss.
struct tc_hot_state {
    uint16_t hotcount[TC_HEAD_SLOTS];
    uint64_t head_pc[TC_HEAD_SLOTS];
#if TC_AOT || TC_JIT
    const void *head_fn[TC_HEAD_SLOTS];
#endif
#if TC_JIT
    /// \brief The translation context each compiled head was recorded in.
    /// \details A compiled trace holds the instructions that were at its
    /// virtual pc, not a way to fetch them, so it is only itself while that pc
    /// still resolves to the same memory and is still executable by the mode
    /// running it. head_key is the host page its instructions were recorded
    /// from, which the code TLB can still confirm at entry; a head whose page no
    /// longer answers, or answers differently, is simply not entered.
    uint64_t head_key[TC_HEAD_SLOTS];
#endif
    uint64_t entries;
};
#endif

#if TC_ONLINE
/// \brief One recorded instruction: its address, its word, and the pc that
/// actually followed it (whatever happened, including raises).
struct tc_online_entry {
    uint64_t vaddr;
    uint64_t next_pc;
    uint32_t insn;
};

/// \brief Online tracer, all storage fixed at translation time.
/// \details One tracer per thread for the experiment; the production shape
/// is a per-machine pool allocated at machine creation. Sizes follow the
/// capture experiments: 1024 trace slots of up to 64 entries.
struct tc_online_state {
    static constexpr uint32_t max_traces = 1024;
    static constexpr uint32_t max_len = 64;
    static constexpr uint32_t min_len = 4;
    static constexpr uint16_t max_penalty = 3;
    struct trace {
        uint64_t head;
        uint32_t len;
        int32_t cycle; // entry index the tail loops back to, or -1
#if TC_JIT
        // Where the compiled body starts and the host page it was recorded
        // from. The head table is rebuilt on every interpret() call, so these
        // are what let an installed trace survive that boundary instead of
        // becoming a head that matches, dispatches nowhere, and blocks its own
        // re-recording for the rest of the run.
        const void *entry;
        uint64_t key;
#endif
        tc_online_entry entries[max_len];
    };
    // The exact head map: an open-addressed table keyed on the head pc, sized
    // well above the pool so it can hold every installed trace at a load factor
    // where a probe almost never leaves its first slot.
    //
    // Exact and non-evicting are both load-bearing, and the direct-mapped table
    // this replaces was neither. A compiled trace is only reachable while its
    // head owns a slot, so with one slot per hash a later install silently
    // unreachable-ed an earlier one -- and because the head stayed in the
    // installed set, it could not be recorded again either, so the loss was
    // permanent. It bound coverage to the table size rather than to the pool,
    // and it bound it worst exactly when the compiled set grew: more
    // compilable instructions meant more traces competing for the same 64
    // slots. Probing instead of replacing costs one comparison in the rare
    // collision and never loses a trace.
    static constexpr uint32_t set_slots = 4096; // >= 4x max_traces, power of two
    trace pool[max_traces];
    uint64_t installed_set[set_slots]; // open-addressed pc set, 0 = empty
#if TC_JIT
    const void *installed_fn[set_slots];  ///< what that head resolves to
    uint64_t installed_key[set_slots];    ///< the host code page it was recorded from
#endif
    uint16_t penalty[TC_HEAD_SLOTS];    // indexed by the head hash, so it sizes with the table
    uint64_t penalty_pc[TC_HEAD_SLOTS];
    uint32_t ntraces;
    bool recording;
    // statistics
    uint64_t installed;
    uint64_t aborted;
    uint64_t flushes;
};
#endif

/// \brief Mutable interpreter loop state committed by the tail-call handler chain when it stops.
/// \details Hot values (pc, insn, the cycle countdown) travel in the fixed
/// handler state instead; pc and mcycle are stored here only when a handler
/// returns to the outer loop. mcycle itself is not kept live: the chain
/// carries a countdown of cycles until the tick end, and the architectural
/// mcycle is materialized as mcycle_tick_end - countdown at the few points
/// that observe it (the privileged handler, chain exits).
template <typename STATE_ACCESS>
struct tc_context {
    i_state_access_fast_addr_t<STATE_ACCESS> pc; ///< Fast pc (vpc + the deposited fetch mapping offset)
    uint64_t mcycle;
    uint64_t mcycle_end;
    uint64_t mcycle_tick_end;
#if TC_PAGE_SEGMENT
    uint64_t mcycle_seg_end; ///< Countdown base: end of the current page segment (never past mcycle_tick_end)
#endif
    i_state_access_fast_addr_t<STATE_ACCESS> fetch_vaddr_page; ///< Fast address of the current code page start
    uint64_t fetch_pma_index;
#if TC_JIT_SHELL
    tc_hot_state hot;
#endif
#if TC_JIT
    uint64_t jit_key; ///< Host page the instruction being recorded came from
    uint64_t jit_enter_rem; ///< Countdown at trace entry, for coverage accounting
#endif
#if TC_ONLINE
    tc_online_state *online;
    uint64_t online_trip_pc;
    uint16_t online_trip_weight;
    bool online_trip;
#endif
};

// Both compilers default to the unified shape: the interpreter's hot state
// pinned in the call-saved registers x23-x27, with the next-instruction
// pre-load, and (under Clang) the preserve_none convention and guaranteed
// tail calls layered on. Every choice can be overridden from the build for
// experiments (-DTC_GLOBAL_REGS=0/1, -DTC_PRELOAD_ENABLED=0/1,
// -DTC_USE_PRESERVE_NONE=0/1, -DTC_MUSTTAIL=).
//
// The register-asm declarations reserve the pinned registers in this
// translation unit (Clang additionally requires -ffixed-x23 through
// -ffixed-x27 on this file's command line, which the tailcall=yes build
// passes), and being call-saved they survive calls into code compiled
// elsewhere. pc crosses the execute_* reference boundary, so handlers bind
// it to a local and sync it at every exit.
#ifndef TC_GLOBAL_REGS
#ifdef __aarch64__
#define TC_GLOBAL_REGS 1
#else
#define TC_GLOBAL_REGS 0
#endif
#endif

#if TC_GLOBAL_REGS && !defined(__aarch64__) && !defined(__x86_64__)
#error "TC_GLOBAL_REGS requires AArch64 or x86-64"
#endif

// The recorder runs in either shape. It needs only the context, which the
// argument shapes derive from the state pointer, and one-instruction chains
// while recording, which the outer loop sets up before the shape split. That
// matters for the copy-and-patch backend on x86-64: the pinned shape cannot
// carry preserve_none there (their registers are the same four), so the
// argument shape is the only one on that host where a stencil gets the
// convention the technique is built around.

// preserve_none composes with pinned registers on AArch64: the pinned state
// is not passed at all, but the convention still frees handlers from
// callee-saved prologue obligations. Both compilers assign its arguments to
// x20-x28 in order (Clang ignoring -ffixed reservations while doing it),
// which is why the pinned set starts at x23, leaving x20-x22 for the
// (accessor, insn) arguments. GCC 16 gains the convention on both targets
// under the same plain attribute spelling Clang uses, so presence is
// probeable everywhere.
#ifndef TC_USE_PRESERVE_NONE
#if __has_attribute(preserve_none)
#define TC_USE_PRESERVE_NONE 1
#else
#define TC_USE_PRESERVE_NONE 0
#endif
#endif

// On x86-64 the two cannot compose: GCC's preserve_none argument registers
// are r12-r15, the pinned set itself, and the assignment does not respect
// the register-asm reservations, so the combination compiles and then
// corrupts state at runtime.
#if TC_GLOBAL_REGS && TC_USE_PRESERVE_NONE && defined(__x86_64__)
#error "pinned registers and preserve_none collide on x86-64; build with TC_USE_PRESERVE_NONE=0"
#endif

#if TC_USE_PRESERVE_NONE
#define TC_CALLCONV __attribute__((preserve_none))
#else
#define TC_CALLCONV
#endif

// The next-instruction pre-load pays for itself only when the register
// budget keeps the extra predicted state (word, dispatch target) in
// registers across the handler body. That holds for the pinned shape
// (AArch64); on the x86-64 args shape it is a measured net loss even
// under preserve_none, the predicted state spilling across the execute
// body, so the default follows the pinned shape alone.
#ifndef TC_PRELOAD_ENABLED
#if TC_GLOBAL_REGS
#define TC_PRELOAD_ENABLED 1
#else
#define TC_PRELOAD_ENABLED 0
#endif
#endif

#ifndef TC_MUSTTAIL
#if defined(__clang__)
#define TC_MUSTTAIL [[clang::musttail]]
#else
#define TC_MUSTTAIL
#endif
#endif


/// \brief Returns the loop context, which lives in the penumbra scratch area.
/// \details The context sits at a constant offset from the processor state,
/// so in the argument-passing shape reaching it consumes no handler
/// argument; the outer loop places it there before dispatching into a
/// chain. The pinned shape keeps a register on it instead (see below).
template <typename STATE_ACCESS>
static FORCE_INLINE tc_context<STATE_ACCESS> *tc_ctx(const STATE_ACCESS a) {
    static_assert(sizeof(tc_context<STATE_ACCESS>) <= sizeof(penumbra_state::scratch));
    static_assert(alignof(tc_context<STATE_ACCESS>) <= alignof(uint64_t));
    // NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast)
    return std::launder(reinterpret_cast<tc_context<STATE_ACCESS> *>(a.get_penumbra().scratch));
}

#if TC_GLOBAL_REGS
// The interpreter's hot state lives in reserved call-saved registers, named
// so the shared handler body text resolves to them directly. pc is one
// exception (execute_* takes it by reference and register globals have no
// address, and Clang restricts named registers to integer types while pc
// carries the fast-address strong type): the register holds the raw fast
// value, TC_ENTER binds a typed local, and TC_SYNC casts it back. The
// fetch tag is treated the same way through the TC_FETCH_TAG macros.
// The pinned set starts at x23 because Clang's preserve_none argument order
// assigns the handler arguments to x20-x22 even when those registers are
// reserved with -ffixed; pinning x22 would let every dispatch clobber pc
// with the instruction word.
// mcycle is not kept live: tc_remaining counts down the cycles until the
// tick end, one fused decrement-and-branch per instruction, and the
// architectural mcycle is materialized as tcc->mcycle_tick_end minus the
// countdown at the few points that observe it. The countdown is unsigned
// but compared as signed: the privileged handler (WFI polling in
// interactive mode) can push mcycle past the tick end, driving it negative.
// The context pointer stays pinned as well, although the context is
// reachable from the processor state: its penumbra offset exceeds the
// AArch64 load immediate range, so deriving it inline puts address
// arithmetic on the mcycle materialization of every memory instruction
// (measured at about 2% aggregate under GCC 15).
#if defined(__aarch64__)
register uint64_t tc_reg_pc asm("x23");
register uint64_t tc_remaining asm("x24");
register uint64_t tc_reg_fetch_page asm("x25");
register tc_context<state_access> *tcc asm("x27");
#else
// x86-64: the four pinned fields fit the callee-saved set with rbp and
// r14 to spare. GCC only: Clang's preserve_none argument order starts at
// r12, so pinned registers and preserve_none cannot coexist here; Clang
// uses the argument-passing shape on this architecture instead.
register uint64_t tc_reg_pc asm("rbx");
register uint64_t tc_remaining asm("r12");
register uint64_t tc_reg_fetch_page asm("r13");
register tc_context<state_access> *tcc asm("r15");
#endif
#define TC_HOT_PARAMS
#define TC_HOT_ARGS
#define TC_ENTER() auto pc = host_addr{tc_reg_pc}
#define TC_SYNC() (tc_reg_pc = static_cast<uint64_t>(pc))
#define TC_FETCH_TAG (host_addr{tc_reg_fetch_page})
#define TC_FETCH_TAG_INVALIDATE()                                                                                      \
    (tc_reg_fetch_page = static_cast<uint64_t>(ensure_fetch_cache_miss(pc)),                                           \
        tcc->fetch_vaddr_page = host_addr{tc_reg_fetch_page})
#define TC_FETCH_TAG_SYNC() (tcc->fetch_vaddr_page = host_addr{tc_reg_fetch_page})
#elif TC_PAGE_SEGMENT
// With page segments the fetch tag is read only by control transfers and
// cold paths, so it leaves the signature and lives in the context alone;
// and with pc as a fast address the fetch needs no offset either, so the
// signature is four slots: accessor, insn, pc, countdown.
#define TC_HOT_PARAMS , i_state_access_fast_addr_t<STATE_ACCESS> pc, uint64_t tc_remaining
#define TC_HOT_ARGS , pc, tc_remaining
#define TC_ENTER() [[maybe_unused]] auto *const tcc = tc_ctx(a)
#define TC_SYNC() ((void) 0)
#define TC_FETCH_TAG (tcc->fetch_vaddr_page)
#define TC_FETCH_TAG_INVALIDATE() (tcc->fetch_vaddr_page = ensure_fetch_cache_miss(pc))
#define TC_FETCH_TAG_SYNC() ((void) 0)
#else
// The fetch tag travels as a handler argument: the pre-load consumes it at
// the head of its dependency chain, where keeping it in a register is worth
// several percent. The tc_context copy is kept coherent at every
// outlined-helper call and chain exit, and remains the storage the outer loop
// and the helpers use. The fetch offset that used to accompany it is gone:
// pc is itself a fast address (section 5.19), so the signature is five slots.
#define TC_HOT_PARAMS                                                                                                  \
    , i_state_access_fast_addr_t<STATE_ACCESS> pc, uint64_t tc_remaining,                                              \
        i_state_access_fast_addr_t<STATE_ACCESS> fetch_vaddr_page
#define TC_HOT_ARGS , pc, tc_remaining, fetch_vaddr_page
#define TC_ENTER() [[maybe_unused]] auto *const tcc = tc_ctx(a)
#define TC_SYNC() ((void) 0)
#define TC_FETCH_TAG fetch_vaddr_page
#define TC_FETCH_TAG_INVALIDATE()                                                                                      \
    (fetch_vaddr_page = ensure_fetch_cache_miss(pc), tcc->fetch_vaddr_page = fetch_vaddr_page)
#define TC_FETCH_TAG_SYNC() (tcc->fetch_vaddr_page = fetch_vaddr_page)
#endif

// The countdown base: with page segments the chain counts to the segment
// end and the true tick end keeps its own field; otherwise they coincide
#if TC_PAGE_SEGMENT
#define TC_CHAIN_END (tcc->mcycle_seg_end)
#else
#define TC_CHAIN_END (tcc->mcycle_tick_end)
#endif
// The architectural cycle counter, derived from the countdown on demand
#define TC_MCYCLE_GET() (TC_CHAIN_END - tc_remaining)
#define TC_MCYCLE_SET(v) (tc_remaining = TC_CHAIN_END - (v))
// One instruction retires: count it and test for the tick boundary
#define TC_TICK_ENDED() (static_cast<int64_t>(--tc_remaining) <= 0)
// NOLINTEND(cppcoreguidelines-macro-usage)
